pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["actual_staffing_information.htm","Actual Staffing Information (Form E-1)","Actual Staffing Information (Form E-1) Top Previous Next The Actual Staffing Information (Form E-1) page captures current year actual data on appl...",""],
["address_editor.htm","Address Editor","Address Editor Top Previous Next Enter your address information below The system may have already filled in certain fields based on information pr...",""],
["address_editor_2.htm","Address Editor","Address Editor Top Previous Next Enter your address information below The system may have already filled in certain fields based on information pr...",""],
["applicant_information.htm","Applicant Information","Applicant Information Top Previous Next The Applicant Information page captures information on applicants including position, applicant category, ...",""],
["applicant_information2.htm","Applicant Information","Applicant Information Top Previous Next The Applicant Information page captures information on applicants including position, applicant category, ...",""],
["applicant_information_editor.htm","Applicant Information Editor","Applicant Information Editor Top Previous Next Enter your contact information below The system may have already filled in certain fields based on ...",""],
["applicant_information_editor_2.htm","Applicant Information Editor","Applicant Information Editor Top Previous Next All fields marked with an asterisk (*) are required. The system may have already filled in certain ...",""],
["application_submission_instruc.htm","Competitive Grant Application Submission Instructions","Competitive Grant Application Submission Instructions Top Previous Welcome to the Legal Services Corporation&#39;s Applicant Information Network (AIN)...",""],
["application_submission_instructions.htm","Competitive Grant Application Introduction","Competitive Grant Application Introduction Top Previous Next Welcome to the Legal Services Corporation&#39;s Applicant Information Network (AIN). Thes...",""],
["board_members.htm","Board Members","Board Members Top Previous Next The Board Members page captures information about board members including name, position and relevant experience. ...",""],
["board_members_editor.htm","Board Members (Form F-2) (All Applicants)","Board Members (Form F-2) (All Applicants) Top Previous Next Applicants who currently have a governing/policy body that conforms to 45 C.F.R. Part ...",""],
["board_members_editor2.htm","Board Members Editor","Board Members Editor Top Previous Next Enter your Board Member information below The system may have already filled in certain fields based on inf...",""],
["board_policies.htm","Board Policies and Practices","Board Policies and Practices Top Previous Next Use the Board Policies and Practices form to describe governing board policies and practices. Compl...",""],
["budget.htm","Budget (Form D)","Budget (Form D) Top Previous Next The Budget (Form D) page captures information on projected expenses, projected revenue, current expenses and cur...",""],
["casehandling.htm","Casehandling Protocols","Casehandling Protocols Top Previous Next Use the Casehandling Protocols form to indicate the Applicant-wide written protocols adopted to ensure th...",""],
["case_development_activities.htm","Case Development Activities","Case Development Activities Top Previous Next Use the Case Development Activities form to indicate the extent to which the listed case development...",""],
["change_password.htm","Change Password","Change Password Top Previous Next To change your password, enter your new password into both the New Password and Confirm New Password fields. Cli...",""],
["chapter_2.htm","LSC Grants Overview","LSC Grants Overview Top Next Welcome to LSC Grants. This application was created to make it possible to submit grant application materials to LSC ...",""],
["conflicts__complaints__perform.htm","Conflicts, Complaints &#38; Performance Evaluations","Conflicts, Complaints &#38; Performance Evaluations Top Previous Next Complete this form by responding to the questions below. Each section in the for...",""],
["contacts.htm","Contacts","Contacts Top Previous Next Enter topic text here. ",""],
["contacts2.htm","Contacts","Contacts Top Previous Next Enter topic text here. ",""],
["continuity_of_operations_plann.htm","Continuity of Operations Planning","Continuity of Operations Planning Top Previous Next Competitive grant Applicants must complete this form for each service area for which they are ...",""],
["copy_existing_task.htm","Copy Existing Task","Copy Existing Task Top Previous Next If you have applied for more than one service area (e.g., basic field and Native American) and wish to copy i...",""],
["copy_task.htm","Copy Task","Copy Task Top Previous Next If you would like to complete a NIC for more than one service area (e.g., basic field and Native American) and wish to...",""],
["current_expenses_editor.htm","Current Year Expenses (Form D-2)","Current Year Expenses (Form D-2) Top Previous Next This Current Expenses (D-2) page captures projected non-LSC expenses for the current year. All ...",""],
["current_revenue_editor.htm","Current Year Revenue (Form D-4)","Current Year Revenue (Form D-4) Top Previous Next The Current Revenue (D-4) page captures total projected support and revenue for the current year...",""],
["current_year_client_services.htm","Current Year Client Services (Form G-1)","Current Year Client Services (Form G-1) Top Previous Next The Current Year Client Services (Form G-1) page captures current year client services. ...",""],
["definitions.htm","Definitions","Definitions Top Previous Next Description of limited and extended service: Limited Service includes counsel and advice, and limited action. Extend...",""],
["definitions2.htm","Definitions","Definitions Top Previous Next Cases are defined as the provision of permissible legal assistance to an eligible client with a legal problem, or se...",""],
["email_editor.htm","Email Address Editor","Email Address Editor Top Previous Next Enter your email address information below The system may have already filled in certain fields based on in...",""],
["email_editor_2.htm","Email Address Editor","Email Address Editor Top Previous Next Enter your email address information below The system may have already filled in certain fields based on in...",""],
["expense_definitions.htm","Expense Definitions","Expense Definitions Top Previous Next 1 Lawyers: This category should include all salaries, wages and profits paid to attorneys (other than for co...",""],
["form_d_1_actual_expenses.htm","Form D-1: Actual Expenses","Form D-1: Actual Expenses Top The Form D-1: Actual Expenses page captures information on actual calendar-year 2011 expenditures of LSC and non-LSC...",""],
["form_d_2.htm","Form D-2: Projected Expenses","Form D-2: Projected Expenses Top Previous Next The Form D-2: Projected Expenses page captures information on projected calendar-year 2011 expendit...",""],
["form_d_3.htm","Form D-3: Actual Support and Revenue","Form D-3: Actual Support and Revenue Top The Form D-3: Actual Support and Revenue page captures information on actual calendar-year 2011 support a...",""],
["form_d_4.htm","Form D-4: Projected Support and Revenue","Form D-4: Projected Support and Revenue Top Previous Next The Form D-4: Projected Support and Revenue page captures information on projected calen...",""],
["form_e_0.htm","Form E-0: Actual Office Information","Form E-0: Actual Office Information Top Actual Office and Staffing Information -- Forms E-0 &#38; E-1 This section contains instructions on updating a...",""],
["form_e_0a.htm","Form E-0(a): Main Office Editor","Form E-0(a): Main Office Editor Top Actual Office and Staffing Information -- Forms E-0 &#38; E-1 This section contains instructions on updating actua...",""],
["form_e_0b.htm","Form E-0(b): Branch Office Editor","Form E-0(b): Branch Office Editor Top Actual Office and Staffing Information -- Forms E-0 &#38; E-1 This section contains instructions on updating act...",""],
["form_e_0c.htm","Form E-0(c): Subrecipient Office Editor","Form E-0(c): Subrecipient Office Editor Top Actual Office and Staffing Information -- Forms E-0 &#38; E-1 This section contains instructions on updati...",""],
["form_e_1a.htm","Form E-1(a): Actual Staffing - Main Office","Form E-1(a): Actual Staffing - Main Office Top See the following pages: Form E-1(a): Staffing Workforce Analysis Form E-1(a): Staff Member Editor ...",""],
["form_e_1a_staff_member.htm","Form E-1(a): Staff Member Editor","Form E-1(a): Staff Member Editor Top Actual Office and Staffing Information -- Forms E-0 &#38; E-1 This section contains instructions on updating actu...",""],
["form_e_1a_workforce.htm","Form E-1(a): Staffing Workforce Analysis","Form E-1(a): Staffing Workforce Analysis Top Actual Office and Staffing Information -- Forms E-0 &#38; E-1 This section contains instructions on updat...",""],
["form_e_1b.htm","Form E-1(b): Actual Staffing - Branch Office","Form E-1(b): Actual Staffing - Branch Office Top Actual Office and Staffing Information -- Forms E-0 &#38; E-1 This section contains instructions on u...",""],
["form_e_1b_staffing_workforce.htm","Form E-1(b): Staffing Workforce Analysis","Form E-1(b): Staffing Workforce Analysis Top Actual Office and Staffing Information -- Forms E-0 &#38; E-1 This section contains instructions on updat...",""],
["form_e_1b_staff_member_editor.htm","Form E-1(b): Staff Member Editor","Form E-1(b): Staff Member Editor Top Actual Office and Staffing Information -- Forms E-0 &#38; E-1 This section contains instructions on updating actu...",""],
["form_e_1c.htm","Form E-1(c): Actual Staffing - Subrecipient Office","Form E-1(c): Actual Staffing - Subrecipient Office Top Actual Office and Staffing Information -- Forms E-0 &#38; E-1 This section contains instruction...",""],
["form_e_1c_staffing_workforce.htm","Form E-1(c): Staffing Workforce Analysis","Form E-1(c): Staffing Workforce Analysis Top Actual Office and Staffing Information -- Forms E-0 &#38; E-1 This section contains instructions on updat...",""],
["form_e_1c_staff_member_editor.htm","Form E-1(c): Staff Member Editor","Form E-1(c): Staff Member Editor Top Actual Office and Staffing Information -- Forms E-0 &#38; E-1 This section contains instructions on updating actu...",""],
["form_e_1_transfer.htm","Form E-1: Transfer Office","Form E-1: Transfer Office Top Actual Office and Staffing Information -- Forms E-0 &#38; E-1 This section contains instructions on updating actual offi...",""],
["form_e_1_transfer2.htm","Form E-1: Transfer Office","Form E-1: Transfer Office Top Actual Office and Staffing Information -- Forms E-0 &#38; E-1 This section contains instructions on updating actual offi...",""],
["form_e_1_transfer3.htm","Form E-1: Transfer Office","Form E-1: Transfer Office Top Actual Office and Staffing Information -- Forms E-0 &#38; E-1 This section contains instructions on updating actual offi...",""],
["form_e_2a.htm","Form E-2(a): Projected Staffing Recipient","Form E-2(a): Projected Staffing Recipient Top Previous Next The projected staffing information for the recipient main and branch offices is to be ...",""],
["form_e_2c.htm","Form E-2(c): Projected Staffing Subrecipient","Form E-2(c): Projected Staffing Subrecipient Top Previous Next The Form E-2(c): Projected Staffing Subrecipient page captures information on proje...",""],
["form_g_1.htm","Form G-1: Projected Case Services","Form G-1: Projected Case Services Top Previous Next The Form G-1: Projected Case Services page captures information on projected calendar year 201...",""],
["form_g_1d.htm","Form G-1(d): Projected Case Services (PAI)","Form G-1(d): Projected Case Services (PAI) Top Previous Next Programs which received 2011 LSC Basic Field-General funding must complete Form G-1(d...",""],
["form_g_2_additional_info.htm","Form G-2: Additional Information Relating to Cases","Form G-2: Additional Information Relating to Cases Top The Form G-2: Additional Information Relating to Cases is a new Form, designed to collect c...",""],
["form_g_3.htm","Form G-3: Actual Case Services (Staff)","Form G-3: Actual Case Services (Staff) Top The Form G-3: Actual Case Services (Staff) page captures information on actual case closures during cal...",""],
["form_g_3d_actual_case_services.htm","Form G-3(d): Actual Case Services (PAI)","Form G-3(d): Actual Case Services (PAI) Top The Form G-3: Actual Case Services (Staff) page captures information on actual case closures during ca...",""],
["form_g_4.htm","Form G-4: Client Age, Ethnicity and Gender","Form G-4: Client Age, Ethnicity and Gender Top The Form G-4: Client Age, Ethnicity and Gender page captures information on the age, ethnicity and ...",""],
["form_g_5.htm","Form G-5: Actual Open Cases (Staff)","Form G-5: Actual Open Cases (Staff) Top The Form G-5: Actual Open Cases (Staff) page captures by service area information on the total number of c...",""],
["form_g_5d.htm","Form G-5(d): Actual Open Cases (PAI)","Form G-5(d): Actual Open Cases (PAI) Top The Form G-5(d): Actual Open Cases (PAI) page captures information on the total number of cases which pri...",""],
["form_g_6.htm","Form G-6: Self-Inspection","Form G-6: Self-Inspection Top See the following pages: Form G-6: Self-Inspection Certification Form G-6: Self-Inspection Summary Form G-6: Self-In...",""],
["form_g_6_cases.htm","Form G-6: Self-Inspection Unreported Non-LSC Case","Form G-6: Self-Inspection Unreported Non-LSC Case Top Form G-6: Self-Inspection captures information on the percentage of sampled CSR cases that h...",""],
["form_g_6_certification.htm","Form G-6: Self-Inspection Certification","Form G-6: Self-Inspection Certification Top Form G-6: Self-Inspection captures information on the percentage of sampled CSR cases that have report...",""],
["form_g_6_summary.htm","Form G-6: Self-Inspection Summary","Form G-6: Self-Inspection Summary Top Form G-6: Self-Inspection captures information on the percentage of sampled CSR cases that have reporting er...",""],
["form_j_1.htm","Form J-1: Components of Actual PAI","Form J-1: Components of Actual PAI Top The Form J-1: Components of Actual PAI page captures information on actual calendar year 2011 private attor...",""],
["form_j_2.htm","Form J-2: Projected Components of PAI","Form J-2: Projected Components of PAI Top Previous Next The Form J-2: Components of Projected PAI page captures information on projected calendar ...",""],
["form_l.htm","Form L: Other Services Narrative","Form L: Other Services Narrative Top Please prepare your narrative according to the instructions provided with our Program Letter 02-9 using a wor...",""],
["form_m.htm","Form M: Other Services Report","Form M: Other Services Report Top Please note the following: To save data, click Save and Calculate/ Save. To continue to the next page, click Sav...",""],
["form_m_1.htm","Form M: Community Legal Education","Form M: Community Legal Education Top Previous Next The Other Services forms are designed to collect information on non case activities (other ser...",""],
["form_m_2.htm","Form M: Pro Se Assistance","Form M: Pro Se Assistance Top Previous Next Pro Se Assistance Form M-2(a) Form M-2(a) is designed to capture general information and assistance pr...",""],
["form_m_3.htm","Form M: Referred Other Services","Form M: Referred Other Services Top Previous Next Referred Referral Form M-3(a) In Form M-3(a) please report referrals that do not qualify as &#39;cas...",""],
["form_m_4.htm","Form M: Outreach","Form M: Outreach Top Previous Next On the Form M: Outreach page please report all the methods used to inform potential clients about the availabil...",""],
["form_m_5.htm","Form M: Indirect Other Services","Form M: Indirect Other Services Top Previous Next The Form M-5: Indirect Other Services page is designed to capture information on non-case activi...",""],
["form_m_6.htm","Form M: Miscellaneous Other Services","Form M: Miscellaneous Other Services Top Previous Next Miscellaneous - Mediation/ADR &#38; Direct Service VI-A This section is designed to capture add...",""],
["grantee_reporting.htm","Grant Activity Reports Instructions","Grant Activity Reports Instructions Top Previous Next Please familiarize yourself with the Grant Activity Reports system before you begin completi...",""],
["grantee_reporting_navigation.htm","Grant Activity Reports Navigation","Grant Activity Reports Navigation Top The following table details the sections within the Grant Activity Reports section. Link Description Home Th...",""],
["grant_application.htm","Grant Application Instructions","Grant Application Instructions Top Previous Next The LSC Request for Proposals (RFP) is available from www.grants.lsc.gov . Applicants must comple...",""],
["grant_application_navigation.htm","Grant Application Navigation","Grant Application Navigation Top Previous Next The following table details the sections within the Grant Application section. Link Description Hom...",""],
["grant_assurances.htm","LSC Grant Assurances (Form C) (All Applicants)","LSC Grant Assurances (Form C) (All Applicants) Top Previous Next The LSC grant assurances (Form C) delineate and clarify the existing laws and reg...",""],
["home.htm","Home","Home Top Previous Next The LSC Grants Home page allows an applicant to either create a Notice of Intent to Compete (NIC) application or view exist...",""],
["home2.htm","Home","Home Top The Grant Activity Reports section below contains a list of all the grantee activity report (GAR) forms assigned to you for submission. G...",""],
["intake_system_technology.htm","Intake System Technology","Intake System Technology Top Previous Next Use the Intake System Technology form to address the technology used in Applicant’s intake process. Eac...",""],
["intake_system_technology_defin.htm","Intake System Technology Definitions","Intake System Technology Definitions Top Previous Next 1. Automated attendant: A telephone system feature that automatically answers incoming call...",""],
["key_staff_members.htm","Key Staff Members","Key Staff Members Top Previous Next The Key Staff Members page captures information about key staff including name, position and relevant experien...",""],
["key_staff_members_editor.htm","Key Staff Members Editor","Key Staff Members Editor Top Previous Next Enter your Key Staff Member information below The system may have already filled in certain fields base...",""],
["legal_needs_assessment_data_co.htm","Legal Needs Assessment Data Collection Methods","Legal Needs Assessment Data Collection Methods Top Previous Next Performance Area 1, Criterion 1 - Periodic comprehensive assessment and ongoing c...",""],
["legal_needs_assessment_data_so.htm","Legal Needs Assessment Data Sources and Tools","Legal Needs Assessment Data Sources and Tools Top Previous Next Performance Area 1, Criterion 1 - Periodic comprehensive assessment and ongoing co...",""],
["legal_work_management.htm","Legal Work Management","Legal Work Management Top Previous Next Use the Legal Work Management form to indicate how frequently the Applicant uses the methods and/or resour...",""],
["lep.htm","LEP Plan and Components","LEP Plan and Components Top Previous Next Use the LEP Plan and Components form to indicate whether Applicant has a written Limited English Profici...",""],
["list_of_references.htm","List of References","List of References Top Previous Next List up to five professional references for the Applicant’s organization or, in the case of a new organizatio...",""],
["logging_in.htm","Logging In","Logging In Top Previous Next Applicants who are not current recipients of LSC funding, click here to register. Applicants who are current recipien...",""],
["lsc_applicant_certification_fo.htm","LSC Applicant Certification (Form I) (All Applicants)","LSC Applicant Certification (Form I) (All Applicants) Top Previous Next Applicants are required to sign and return Applicant Certification (Form I...",""],
["lsc_applicant_information.htm","LSC Applicant Information","LSC Applicant Information Top Previous Next Click LSC Applicant Information on the LSC Grants Login page to view information shown below in the sc...",""],
["lsc_competitive_grant_proposal.htm","LSC Competitive Grant Proposal Narrative Instruction (Competition Applicants Only)","LSC Competitive Grant Proposal Narrative Instruction (Competition Applicants Only) Top Previous Next Click here to view the instruction . ",""],
["lsc_grants_overview.htm","LSC Grants Overview","LSC Grants Overview Top Next Welcome to LSC Grants. This application was created to make it possible to submit grant application materials to LSC ...",""],
["lsc_grant_renewal_narrative_in.htm","LSC Grant Renewal Narrative Instruction (Renewal Applicants Only)","LSC Grant Renewal Narrative Instruction (Renewal Applicants Only) Top Previous Next Click here to view the instruction . ",""],
["lsc_recipient_information.htm","LSC Recipient Information","LSC Recipient Information Top Previous Next Click LSC Recipient Information on the LSC Grants Login page to view information shown below in the sc...",""],
["main.htm","Main","Main Top Previous Next The Main page provides a summary of your Notice of Intent to Compete (NIC) application. The Validation Summary below displa...",""],
["main2.htm","Main (Renewal)","Main (Renewal) Top Previous Next The Main page provides a summary of your application. The Validation Summary below displays the status of your ap...",""],
["main_application.htm","Main","Main Top Previous Next The Main page provides a summary of your application. The Validation Summary below displays the status of your application,...",""],
["navigation.htm","NIC Navigation","NIC Navigation Top Previous Next The following table details the sections within the Notice of Intent to Compete (NIC) section. Link Description H...",""],
["nic_instructions.htm","Notice of Intent to Compete (NIC) section","Notice of Intent to Compete (NIC) section Top Previous Next These instructions describe how to complete the Notice of Intent to Compete (NIC). Com...",""],
["nic_navigation.htm","Notice of Intent to Compete (NIC) Navigation","Notice of Intent to Compete (NIC) Navigation Top Previous Next The following table details the sections within the Notice of Intent to Compete (NI...",""],
["notice_of_intent_to_compete.htm","Notice of Intent to Compete (NIC) Instructions (All Applicants)","Notice of Intent to Compete (NIC) Instructions (All Applicants) Top Previous Next In order to submit a Grant Application, an Applicant must first ...",""],
["organizational_overview.htm","Organizational Overview","Organizational Overview Top Previous Next LSC requires each Applicant to provide an overview of its organization and delivery system. The overview...",""],
["overview.htm","Notice of Intent to Compete Submission Instructions","Notice of Intent to Compete Submission Instructions Top Previous Next These instructions describe how to complete the Notice of Intent to Compete ...",""],
["pai_projected_expenses.htm","PAI Projected Expenses (Form D-13) (All Applicants)","PAI Current Year Expenses (Form D-13) (All Applicants) Top Previous Next The PAI Current Year Expenses (Form D-13) page captures projected expense...",""],
["password_retrieval.htm","Password Retrieval","Password Retrieval Top Previous Next Enter your primary email address and click Submit. Your password will be sent to the primary email address. T...",""],
["policy_board_structure.htm","Current Year Governing/Policy Body Structure (Form F) (All Applicants)","Current Year Governing/Policy Body Structure (Form F) (All Applicants) Top Previous Next The Current Year Governing/Policy Body Structure (Forms F...",""],
["policy_board_structure_editor.htm","Policy Board Structure (Form F-1) (All Applicants)","Policy Board Structure (Form F-1) (All Applicants) Top Previous Next Applicants who currently have a governing/policy body that conforms to 45 C.F...",""],
["professional_reference_editor.htm","Professional Reference Editor","Professional Reference Editor Top Previous Next Enter the following information for each professional reference: * Name * Title * Organization * A...",""],
["profile.htm","Profile","Profile Top Previous Next Enter topic text here. ",""],
["projected_expenditures.htm","Projected Expenditures by Type of Activity (Form G-12) (All Applicants)","Projected Expenditures by Type of Activity (Form G-12) (All Applicants) Top Previous Next The Projected Expenditures by Type of Activity (Form G-1...",""],
["projected_expenses_editor.htm","Projected Expenses (Form D-12) (All Applicants)","Projected Expenses (Form D-12) (All Applicants) Top Previous Next This Projected Expenses (Form D-12) page captures projected LSC and non-LSC expe...",""],
["projected_revenue_editor.htm","Projected Revenue (Form D-14) (All Applicants)","Projected Revenue (Form D-14) (All Applicants) Top Previous Next The Projected Revenue (Form D-14) page captures projected support and revenue dat...",""],
["project_information.htm","Project Information","Project Information Top Previous Next The Project Information page allows the applicant to review information about the project including Service ...",""],
["project_information2.htm","Project Information","Project Information Top Previous Next The Project Information page allows the applicant to review information about the project including Service ...",""],
["pvt_att_involvement.htm","Private Attorney Involvement","Private Attorney Involvement Top Previous Next Use the Private Attorney Involvement form to address the Applicant’s PAI participation. Complete th...",""],
["recruit_pvt_atty.htm","Methods Used to Recruit Private Attorneys","Methods Used to Recruit Private Attorneys Top Previous Next Use the Methods Used to Recruit Private Attorneys form to indicate how often the Appli...",""],
["registration.htm","Registration","Registration Top Previous Next Only applicants who are not current recipients of LSC funding should complete the Registration page. Enter all requ...",""],
["retain_pvt_atty_volunteers.htm","Methods Used to Retain Private Attorneys Volunteers","Methods Used to Retain Private Attorneys Volunteers Top Previous Next Use the Methods Used to Retain Private Attorney Volunteers form to indicate ...",""],
["review_and_submit.htm","Review and Submit","Review and Submit Top Previous Next The Submission section indicates whether you are able to submit your Notice of Intent to Compete application. ...",""],
["review_and_submit10.htm","Review and Submit","Review and Submit Top Sample screen shot ",""],
["review_and_submit11.htm","Review and Submit","Review and Submit Top Sample screen shot ",""],
["review_and_submit12.htm","Review and Submit","Review and Submit Top Sample screen shot ",""],
["review_and_submit13.htm","Review and Submit","Review and Submit Top Sample screen shot ",""],
["review_and_submit14.htm","Review and Submit","Review and Submit Top Sample Screen Shot ",""],
["review_and_submit15.htm","Review and Submit","Review and Submit Top Previous Next Sample screen shot ",""],
["review_and_submit16.htm","Review and Submit","Review and Submit Top Previous Next Sample screen shot ",""],
["review_and_submit17.htm","Review and Submit","Review and Submit Top Previous Next Sample screen shot ",""],
["review_and_submit18.htm","Review and Submit","Review and Submit Top Previous Next Sample screen shot ",""],
["review_and_submit19.htm","Review and Submit","Review and Submit Top Sample screen shot ",""],
["review_and_submit2.htm","Review and Submit","Review and Submit Top Previous Next The Submission section below indicates whether you are able to submit your application. If all pages in the ap...",""],
["review_and_submit20.htm","Review and Submit","Review and Submit Top Sample screen shot ",""],
["review_and_submit21.htm","Review and Submit","Review and Submit Top Sample screen shot ",""],
["review_and_submit22.htm","Review and Submit","Review and Submit Top Sample screen shot ",""],
["review_and_submit23.htm","Review and Submit","Review and Submit Top Previous Next Sample screen shot ",""],
["review_and_submit24.htm","Review and Submit","Review and Submit Top Sample screen shot ",""],
["review_and_submit3.htm","Review and Submit","Review and Submit Top Sample screen shot ",""],
["review_and_submit4.htm","Review and Submit","Review and Submit Top Sample Screen Shot ",""],
["review_and_submit5.htm","Review and Submit","Review and Submit Top Sample screen shot ",""],
["review_and_submit6.htm","Review and Submit","Review and Submit Top Sample screen shot ",""],
["review_and_submit7.htm","Review and Submit","Review and Submit Top Sample screen shot ",""],
["review_and_submit8.htm","Review and Submit","Review and Submit Top Sample screen shot ",""],
["review_and_submit9.htm","Review and Submit","Review and Submit Top Sample screen shot ",""],
["review_and_submit_renewal.htm","Review and Submit (Renewal)","Review and Submit (Renewal) Top Previous The Submission section below indicates whether you are able to submit your application. If all pages in t...",""],
["service_areas_in_competition.htm","Service Areas in Competition for LSC Grants","Service Areas in Competition for LSC Grants Top Previous Next To begin preparing a Notice of Intent to Compete (NIC), select one of the Service Ar...",""],
["software.htm","Technology (Form K)","Technology (Form K) Top Previous Next Instructions The Technology Form (Form K) captures information on Applicant’s current technology in place at...",""],
["submission_requirements.htm","Submission Requirements","Submission Requirements Top Submission Requirements All D Forms and the G-3, G-4 and G-5 Forms must be submitted separately for each service area....",""],
["support_and_revenue_definition.htm","Support and Revenue Definitions","Support and Revenue Definitions Top Previous Next 10 LSC General Basic Field Grant: LSC funding that is allocated based upon the poverty populatio...",""],
["technology.htm","Current Applicant Technology (Form K-1) (All Applicants)","Current Applicant Technology (Form K-1) (All Applicants) Top Previous Next The Current Applicant Technology (Form K-1) page captures data on Appli...",""],
["technology_budget_form_d_15.htm","Technology Budget (Form D-15)","Technology Budget (Form D-15) Top Previous Next Instructions Form D-15 captures projected LSC and non-LSC expenses for carrying out Applicant’s Te...",""],
["technology_definitions.htm","Technology Definitions","Technology Definitions Top Previous Next 1. A2J Author: This is a user friendly interface for automated forms interviews which incorporates websit...",""],
["telephonefax_editor.htm","Telephone/Fax Editor","Telephone/Fax Editor Top Previous Next Enter your telephone/fax information below The system may have already filled in certain fields based on in...",""],
["telephonefax_editor_2.htm","Telephone/Fax Editor","Telephone/Fax Editor Top Previous Next Enter your telephone/fax information below The system may have already filled in certain fields based on in...",""],
["training.htm","Training","Training Top Previous Next Use the Training form to indicate what proportion of the staff received each type of training in the last twenty-four m...",""],
["uploads.htm","Uploads (Competition)","Uploads (Competition) Top Previous Next The uploads listed in the Upload Checklist below are required for this application. To upload a document: ...",""],
["uploads_editor.htm","Uploads Editor","Uploads Editor Top Previous Next Please follow these instructions to upload the document. 1. If available, download the template and save the file...",""],
["uploads_renewal.htm","Uploads (Renewal)","Uploads (Renewal) Top Previous Next The uploads listed in the Upload Checklist below are required for this application. To upload a document: 1. I...",""],
["upload_editor.htm","Upload Form L: Service Narrative","Upload Form L: Service Narrative Top Please follow these instructions to upload the document. 1. If available, download the template and save the ...",""]];
