rem set path=%path%;C:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\Binn;

set MSSQLSERVER_NAME=<<ENTER SERVER NAME HERE>>
set MSSQLSERVER_DBNAME=<<ENTER DATABASE NAME HERE>>

REM *****************************
REM EXECUTE	POST VERSION 5.3.5 UPGRADE SCRIPTS
REM *****************************

sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 002_ALTER_VIEW_vSUBMITTEDFILES.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 007_ALTER_vEXTERNAL_REVIEW_APPLICATIONS_LIST.sql