ALTER TABLE LSC_a_PRO_BONO_SUBCATEGORY
	ADD weighting INT

GO

UPDATE LSC_a_PRO_BONO_SUBCATEGORY
	SET weighting = 10
	WHERE id IN (1, 2, 5, 6)

UPDATE LSC_a_PRO_BONO_SUBCATEGORY
	SET weighting = 15
	WHERE id IN (3, 4, 7, 8)