ALTER TABLE LSC_PRO_BONO_RISK_ASSESSMENT_REVIEW
	ALTER COLUMN audited_financial_statements_desc varchar(MAX) 

ALTER TABLE LSC_PRO_BONO_RISK_ASSESSMENT_REVIEW
	ALTER COLUMN pai_waivers_desc varchar(MAX) 

ALTER TABLE LSC_PRO_BONO_RISK_ASSESSMENT_REVIEW
	ALTER COLUMN tig_performance_desc varchar(MAX)

ALTER TABLE LSC_PRO_BONO_RISK_ASSESSMENT_REVIEW
	ALTER COLUMN special_grant_conditions_desc varchar(MAX)

ALTER TABLE LSC_PRO_BONO_RISK_ASSESSMENT_REVIEW
	ALTER COLUMN oce_compliance_fiscal_reviews_desc varchar(MAX)

ALTER TABLE LSC_PRO_BONO_RISK_ASSESSMENT_REVIEW
	ALTER COLUMN opp_quality_reviews_desc varchar(MAX)

ALTER TABLE LSC_PRO_BONO_RISK_ASSESSMENT_REVIEW
	ALTER COLUMN irs_form_990_desc varchar(MAX)

ALTER TABLE LSC_PRO_BONO_RISK_ASSESSMENT_REVIEW
	ALTER COLUMN oig_investigation_matters_desc varchar(MAX)

ALTER TABLE LSC_PRO_BONO_RISK_ASSESSMENT_REVIEW
	ALTER COLUMN issue_contractor_subgrantee_desc varchar(MAX)

ALTER TABLE LSC_PRO_BONO_RISK_ASSESSMENT_REVIEW
	ALTER COLUMN other_comments varchar(MAX)
