UPDATE LSC_a_REVIEW_CATEGORY SET description = 'PA1, C1, 2, and 3' WHERE id = 1
UPDATE LSC_a_REVIEW_CATEGORY SET description = 'PA1, C4' WHERE id = 2
UPDATE LSC_a_REVIEW_CATEGORY SET description = 'PA2, C1' WHERE id = 4
UPDATE LSC_a_REVIEW_CATEGORY SET description = 'PA2, C2 and 3' WHERE id = 5
UPDATE LSC_a_REVIEW_CATEGORY SET description = 'PA3, C1a' WHERE id = 6
UPDATE LSC_a_REVIEW_CATEGORY SET description = 'PA3, C1b' WHERE id = 7
UPDATE LSC_a_REVIEW_CATEGORY SET description = 'PA3, C1c' WHERE id = 8
UPDATE LSC_a_REVIEW_CATEGORY SET description = 'PA3, C2' WHERE id = 9
UPDATE LSC_a_REVIEW_CATEGORY SET description = 'PA3, C3 and 4' WHERE id = 10
UPDATE LSC_a_REVIEW_CATEGORY SET description = 'PA4, C1' WHERE id = 11
UPDATE LSC_a_REVIEW_CATEGORY SET description = 'PA4, C2' WHERE id = 12
UPDATE LSC_a_REVIEW_CATEGORY SET description = 'PA4, C3' WHERE id = 13
UPDATE LSC_a_REVIEW_CATEGORY SET description = 'PA4, C4' WHERE id = 14
UPDATE LSC_a_REVIEW_CATEGORY SET description = 'PA4, C5' WHERE id = 15
UPDATE LSC_a_REVIEW_CATEGORY SET description = 'PA4, C6' WHERE id = 16
UPDATE LSC_a_REVIEW_CATEGORY SET description = 'PA4, C7' WHERE id = 17
UPDATE LSC_a_REVIEW_CATEGORY SET description = 'PA4, C9' WHERE id = 18
