CREATE VIEW vLSC_SUBRECIPIENT_BUDGET_TOTAL

AS

SELECT sb.lsc_subrecipient_budget_id,
	ISNULL(sb.lawyers, 0)
	+ ISNULL(sb.paralegals, 0)
	+ ISNULL(sb.other_staff, 0)
	+ ISNULL(sb.employee_benefits, 0) AS personnel,
	ISNULL(sb.space_rent, 0)
	+ ISNULL(sb.space_mortgage, 0)
	+ ISNULL(sb.space_other, 0)
	+ ISNULL(sb.equip_rental, 0)
	+ ISNULL(sb.off_supplies, 0)
	+ ISNULL(sb.telephone, 0)
	+ ISNULL(sb.travel_board, 0)
	+ ISNULL(sb.travel_staff, 0)
	+ ISNULL(sb.training_board, 0)
	+ ISNULL(sb.training_staff, 0)
	+ ISNULL(sb.library, 0)
	+ ISNULL(sb.insurance, 0)
	+ ISNULL(sb.dues, 0)
	+ ISNULL(sb.audit, 0)
	+ ISNULL(sb.litigation, 0)
	+ ISNULL(sb.property_acq, 0)
	+ ISNULL(sb.purchase_pmt, 0)
	+ ISNULL(sb.contract_client, 0)
	+ ISNULL(sb.contract_applicant, 0)
	+ ISNULL(sb.other, 0) AS non_personnel,
	ISNULL(sb.lawyers, 0)
	+ ISNULL(sb.paralegals, 0)
	+ ISNULL(sb.other_staff, 0)
	+ ISNULL(sb.employee_benefits, 0)
	+ ISNULL(sb.space_rent, 0)
	+ ISNULL(sb.space_mortgage, 0)
	+ ISNULL(sb.space_other, 0)
	+ ISNULL(sb.equip_rental, 0)
	+ ISNULL(sb.off_supplies, 0)
	+ ISNULL(sb.telephone, 0)
	+ ISNULL(sb.travel_board, 0)
	+ ISNULL(sb.travel_staff, 0)
	+ ISNULL(sb.training_board, 0)
	+ ISNULL(sb.training_staff, 0)
	+ ISNULL(sb.library, 0)
	+ ISNULL(sb.insurance, 0)
	+ ISNULL(sb.dues, 0)
	+ ISNULL(sb.audit, 0)
	+ ISNULL(sb.litigation, 0)
	+ ISNULL(sb.property_acq, 0)
	+ ISNULL(sb.purchase_pmt, 0)
	+ ISNULL(sb.contract_client, 0)
	+ ISNULL(sb.contract_applicant, 0)
	+ ISNULL(sb.other, 0) AS total,
	CASE WHEN 	ISNULL(sb.lawyers, 0)
	+ ISNULL(sb.paralegals, 0)
	+ ISNULL(sb.other_staff, 0)
	+ ISNULL(sb.employee_benefits, 0)
	+ ISNULL(sb.space_rent, 0)
	+ ISNULL(sb.space_mortgage, 0)
	+ ISNULL(sb.space_other, 0)
	+ ISNULL(sb.equip_rental, 0)
	+ ISNULL(sb.off_supplies, 0)
	+ ISNULL(sb.telephone, 0)
	+ ISNULL(sb.travel_board, 0)
	+ ISNULL(sb.travel_staff, 0)
	+ ISNULL(sb.training_board, 0)
	+ ISNULL(sb.training_staff, 0)
	+ ISNULL(sb.library, 0)
	+ ISNULL(sb.insurance, 0)
	+ ISNULL(sb.dues, 0)
	+ ISNULL(sb.audit, 0)
	+ ISNULL(sb.litigation, 0)
	+ ISNULL(sb.property_acq, 0)
	+ ISNULL(sb.purchase_pmt, 0)
	+ ISNULL(sb.contract_client, 0)
	+ ISNULL(sb.contract_applicant, 0)
	+ ISNULL(sb.other, 0) = ISNULL(ws.subgrant_amount, -1) THEN 1 ELSE 0 END AS matches_subgrant_amount
	FROM LSC_SUBRECIPIENT_BUDGET sb
		LEFT JOIN LSC_WFTA_SUBGRANT ws ON sb.wf_task_assignment_id = ws.wf_task_assignment_id
