rem set path=%path%;C:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\Binn;

set MSSQLSERVER_NAME=<<ENTER SERVER NAME HERE>>
set MSSQLSERVER_DBNAME=<<ENTER DATABASE NAME HERE>>

REM *****************************
REM EXECUTE	POST VERSION 5.3 UPGRADE SCRIPTS
REM *****************************

sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 01_Update_a_REPORT_OUTPUT_DEFINITION.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 02_Alter_vTOTAL_PAYMENT.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 03_Alter_vTOTAL_PAYMENT_SCHEDULED.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 04_Alter_tables.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 05_Alter_s_SHAREPOINT_INTEGRATION.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 06_Update_a_STANDARD_FORMS.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 07_Alter_vThirdPartyUploads.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 08_Update_s_SHAREPOINT_INTEGRATION.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 09_Create_vReviewCycleHasActiveWfta.sql

