

EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58937
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58901
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58895
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58929
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58923
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58907
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58879
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58881
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58917
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58935
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58915
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58887
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58919
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58885
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58893
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58778
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58905
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58927
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58781
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58931
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58877
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58836
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58990
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58889
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58911
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58883
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58783
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58939
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58913
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58897
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58891
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58921
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58899
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58925
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58933
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58992
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58909
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58903
EXEC spLSC_XFER_TIG_BUDGET_TO_WFTA @WfTaskAssignmentID =	58785


