<%@ Page Language="vb" AutoEventWireup="true" Inherits="Core.Web.cCorePage"%>
<%@ Register Tagprefix='Core' Namespace='Core.Web.SvrCtls' Assembly='Core' %>
<%--<Core:cUserCtlLoader ID='ctlStyleLoader'
		CtlID='ctlStyles' 
		Src='Implementation/CSS/DefaultStyles.ascx'
		runat='server'/>--%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
  <head>
		<title>Browser Compatibility</title>
		<link rel="stylesheet" type="text/css" href="<%=WebAppl.DefaultStylesPath%>" />
		<link rel="stylesheet" type="text/css" href="<%=WebAppl.ClientStylesPath%>" />
  </head>
  <body>
	<form id="Form1" method="post" runat="server">
		<table runat='server' width='100%' ID="Table1">
			<tr>
				<td class='SeparatorHdg'>
					<b>Recommended Browsers and Operating Systems</b>
				</td>
			</tr>
		</table>
		<p>
		We recommend the following browsers and operating systems for compatibility with our system:
		</p>
		<p>
		For Microsoft Windows 98 / Microsoft Internet Explorer 5.01
		</p>
		<p>
		For Microsoft Windows 2000:  Netscape Navigator 7.1 or Microsoft Internet Explorer 6.0
		</p>
		<p>
		For Microsoft Windows XP:  Netscape Navigator 7.1 or Microsoft Internet Explorer 6.0
		</p>
		<p>
		For Mac OS 9.2:  Netscape Navigator 6.2.3 or Internet Explorer 5.1
		</p>
		<p>
		For Mac OS 10.3.x:  Netscape Navigator 7.1 or Safari 1.1.1
		</p>
		<p>
		For Linux Kernel 2.4:  Netscape Navigator 7.1 or Mozilla 0.9.2.1
		</p>
		<p>You may download the latest version of Internet Explorer <a target="_blank" href="http://www.microsoft.com/windows/ie/default.asp">here</a>.</p>
		<p>You may download the latest version of Netscape Navigator <a href="http://channels.netscape.com/ns/browsers/download.jsp" target="_blank">here</a>.</p>
		
		<table runat='server' width='100%'>
			<tr>
				<td class='SeparatorHdg'>
					<b>Adobe PDF Reader Support</b>
				</td>
			</tr>
		</table>
		<p>
		Please use Adobe Reader version 5.0 or 6.0 to view any PDF files generated by this system. 
		</P>
		You may download the latest version of Adobe Reader <a href="http://www.adobe.com/products/acrobat/readstep2.html" target="_blank">here</a>.
		<P>
		</P>

    </form>
    <script type="text/javascript">
		var trackKey = new String('<%=WebAppl.GetSystemSetting("GoogleAnalytics") %>');
		if (trackKey != "") {
			var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
			document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
		}
	</script>
	<script type="text/javascript">
		var trackKey = new String('<%=WebAppl.GetSystemSetting("GoogleAnalytics") %>');
		if (trackKey != "") {
			var pageTracker = _gat._getTracker(trackKey);
			pageTracker._trackPageview();
		}
	</script>
  </body>
</html>
