CREATE VIEW vLSC_CSR_TOTAL

AS


SELECT lsc_csr_id,
	ISNULL(A,0) + ISNULL(B,0) + ISNULL(C,0) + 
		ISNULL(D,0) + ISNULL(E,0) + ISNULL(F,0) + 
		ISNULL(G,0) + ISNULL(H,0) + ISNULL(I,0) + 
		ISNULL(Ia,0) + ISNULL(Ib,0) + ISNULL(Ic,0) + 
		ISNULL(J,0) + ISNULL(K,0) + ISNULL(L,0) total
	FROM LSC_CSR