pageinfo = [[1234387809,7234],
	[1229628523,3991],
	[1217532939,11698],
	[1217533111,14055],
	[1204306695,3141],
	[1204322613,5032],
	[1217351099,13331],
	[1214940641,5790],
	[1217352293,8026],
	[1217352279,12047],
	[1217352177,19366],
	[1240859597,7481],
	[1240861659,22925],
	[1217532363,4215],
	[1217532585,8722],
	[1217602983,8218],
	[1217604641,9797],
	[1217603319,19674],
	[1217604465,12245],
	[1217604453,11636],
	[1217352725,11373],
	[1217605247,7343],
	[1217602839,7223],
	[1217602917,10982],
	[1215020511,5648],
	[1217351971,12389],
	[1228871599,4357],
	[1228872085,8492],
	[1206996301,4919],
	[1229628117,18309],
	[1217347299,4876],
	[1234194781,10690],
	[1217531583,4112],
	[1234387827,9682],
	[1217602635,5901],
	[1217602695,6798],
	[1217602793,10724],
	[1214577835,7132],
	[1214578459,13263],
	[1238711215,6572],
	[1228934695,6553],
	[1238711233,9942],
	[1234387855,15437],
	[1214936539,7452],
	[1231264097,7583],
	[1217346635,9552],
	[1214936533,8223],
	[1214936531,7394],
	[1217347243,15630],
	[1217347249,20760],
	[1231266909,25620],
	[1231266899,25758],
	[1238710581,24342],
	[1217347267,20296],
	[1217347275,20865],
	[1214936681,13501],
	[1231265705,20643],
	[1231266893,25664],
	[1217606255,16367],
	[1238710621,24135],
	[1217347263,21651],
	[1217347269,21816],
	[1214936599,9854],
	[1217347283,21733],
	[1214578533,3829],
	[1217352077,6161],
	[1217352155,18296],
	[1229628807,28317],
	[1204305691,5326],
	[1217352013,9974],
	[1217351997,11847],
	[1217352031,16421],
	[1217347231,15908],
	[1217351845,4164],
	[1217351851,13485],
	[1234385763,4078],
	[1217423719,24689],
	[1234445893,5282],
	[1234445895,9263],
	[1228846153,7635],
	[1219183197,7514],
	[1237296683,7575],
	[1224175173,5621],
	[1219183549,7838],
	[1213978219,13471],
	[1217346477,6277],
	[1234369813,11065],
	[1206889023,6578],
	[1204137985,6078],
	[1202774687,13986],
	[1231185815,12392],
	[1203776167,7365],
	[1213978631,13079],
	[1213978727,13695],
	[1213978519,14465],
	[1213978425,15658],
	[1217346505,10721],
	[1213978653,9983],
	[1203780387,4140],
	[1213978887,9000],
	[1204153241,4161],
	[1204138041,7356],
	[1231186125,6979],
	[1204322507,11483],
	[1204322515,11943],
	[1217347223,18831],
	[1204322511,11468],
	[1231186209,12604],
	[1204138247,7725],
	[1206975145,13000],
	[1214421425,14607],
	[1214421561,10219],
	[1214421469,10258],
	[1231185863,15013],
	[1214421489,10481],
	[1214421509,9891],
	[1231186253,13636],
	[1240859485,5929],
	[1231186291,4219],
	[1214423161,8953],
	[1204322533,6567],
	[1214423113,12254],
	[1234369005,16268],
	[1204322573,11710],
	[1240859503,6057],
	[1217347219,24800],
	[1217347219,21076],
	[1217555175,6385],
	[1217532153,3103],
	[1217946537,10048],
	[1234384617,96709],
	[1202316023,3874],
	[1217428287,23997],
	[1217533177,7836],
	[1217533861,12023],
	[1217554947,6184],
	[1217556181,12211],
	[1217555881,11818],
	[1217556421,7594],
	[1217607591,5724],
	[1217611323,22215],
	[1217611279,12995],
	[1217611159,13355],
	[1217608869,4253],
	[1217610797,6254],
	[1217600105,8562],
	[1231251923,8212],
	[1234384465,5202],
	[1231260181,5515],
	[1217554093,7936],
	[1217534083,10479],
	[1217554673,6830],
	[1225468185,16142],
	[1217554355,12728],
	[1217599945,7125],
	[1217599493,12904],
	[1217599701,18302],
	[1217599117,12499],
	[1217598689,3554],
	[1217598665,4063],
	[1231865881,8109],
	[1231866901,2982],
	[1231867053,5429],
	[1217596091,14580],
	[1231866599,11414],
	[1231865703,16149],
	[1217597699,15282],
	[1206802119,4527],
	[1217599927,10550],
	[1217600049,5986],
	[1217348881,8892],
	[1217426239,11478],
	[1217426617,15281],
	[1224174941,24155],
	[1220460801,19264],
	[1217426031,5745],
	[1219163497,8201],
	[1204321595,3385],
	[1213723573,6953],
	[1213723023,14369],
	[1213724073,8461],
	[1204755001,4010],
	[1213724177,7468],
	[1219249033,7439],
	[1219248965,7224],
	[1219251371,14641],
	[1213729911,7972],
	[1219251377,6861],
	[1234388347,3788],
	[1234384523,3384],
	[1234388169,6843],
	[1204321523,6821],
	[1234380073,12630],
	[1234370117,15484],
	[1217531859,12315],
	[1207058981,5318],
	[1217351281,2808],
	[1217351325,13004],
	[1207060501,6075],
	[1214580181,10061],
	[1214580297,11336],
	[1207061207,9368],
	[1214579673,7631],
	[1217351361,2873],
	[1217351383,2795],
	[1217348735,10723],
	[1213733033,6150],
	[1217346371,5234],
	[1219176373,16736],
	[1213737295,15653],
	[1204755169,5458],
	[1204755357,5275],
	[1204757143,5724],
	[1234384991,12462],
	[1204756007,5221],
	[1204757161,4568],
	[1228848403,3962],
	[1228848319,10164],
	[1228848297,22333],
	[1228848433,5714],
	[1228848481,3514],
	[1228848523,7975],
	[1228848513,20475],
	[1228848499,19907],
	[1228848343,7467],
	[1228848373,12928],
	[1217346399,7264],
	[1213813721,11247],
	[1201966917,4049],
	[1228848617,7004],
	[1228848639,7853],
	[1228848663,6848],
	[1228848703,8163],
	[1228848691,28600],
	[1228848669,28519],
	[1213815773,18656],
	[1228848769,7050],
	[1202315721,16488],
	[1225468207,22739],
	[1228848835,15426],
	[1228848813,31133],
	[1228848863,5057],
	[1217347193,17271],
	[1217347193,24410],
	[1217346373,5315],
	[1217895959,16363],
	[1213738085,15622],
	[1204755217,5440],
	[1213729265,7350]];
pagedata = [ ["./administration.htm","Administration","﻿Administration The Administration section of the Easygrants Manager includes the tools for managing the setup of the Easygrants system. This incl...",""],
["./administration_budget.htm","Budget","﻿Budget The Budget section provides the functionality to create and maintain budgets and budget line items for specific funding cycles. To access ...",""],
["./administration_budget_managing_budget_categories.htm","Managing Budget Categories","﻿Managing Budget Categories To search for the appropriate funding cycle: 1. Select a Program Name from the drop-down list. The page refreshes with...",""],
["./administration_budget_managing_budget_line_items.htm","Managing Budget Line Items","﻿Managing Budget Line Items To search for the appropriate budget category: 1. Select a Program Name from the drop-down list. The page refreshes wi...",""],
["./administration_configuration.htm","Configuration","﻿Configuration The Configuration section provides the functionality to create new Programs, Funding Opportunities, and Funding Cycles. For each Fu...",""],
["./administration_contact_categories.htm","Contact Categories","﻿Contact Categories The contact categories provides the functionality to group person contact records where there is no common data between the re...",""],
["./administration_contact_categories_managing_contact_categories.htm","Managing Contact Categories","﻿Managing Contact Categories To add a contact category: 1. Click on the Add button in the Contact Category section of the Contact Category page. T...",""],
["./administration_content_manager.htm","Content Manager","﻿Content Manager The content manager provides the functionality to update task related instructional text providing clear directions to the assign...",""],
["./administration_content_manager_copy_instructional_content.htm","Copying Instructional Content","﻿Copying Instructional Content To copy the content: 1. Click on the Copy button next to the Task field in the Content Management section of the Co...",""],
["./administration_content_manager_managing_instructional_content.htm","Managing Instructional Content","﻿Managing Instructional Content To add instructional content for a particular task: 1. Select the Program Name. The page refreshes and displays th...",""],
["./administration_eligibility_builder.htm","Eligibility Builder","﻿Eligibility Builder The Eligibility Builder section of the Administration module allows the creation of eligibility quiz templates that can be se...",""],
["./administration_email_templates.htm","E-mail Templates","﻿E-mail Templates The e-mail templates provide the functionality to create standard e-mail communications that can be used as part of the workflow...",""],
["./administration_email_templates_managing_email_templates.htm","Managing E-mail Templates","﻿Managing E-mail Templates To add an e-mail template: 1. Click on the Add button in the Add or Edit E-mail Templates section of the E-mail Templat...",""],
["./administration_faq_manager.htm","FAQ Manager","﻿FAQ Manager The FAQ Manager feature allows you to manage frequently asked questions that can assist your user community with their activity withi...",""],
["./administration_faq_manager_managing_faqs.htm","Managing FAQs","﻿Managing FAQs To add a new FAQ: 1. Click on the Add button in the FAQ Manager section of the FAQ Manager page. The FAQ Editor page displays. 2. E...",""],
["./administration_funding_cycle.htm","Funding Cycles","﻿Funding Cycles All Funding Cycles for a selected Program/Funding Opportunity are listed in order of the Funding Cycle ID in the Funding Cycle Man...",""],
["./administration_funding_cycle_copy_a_funding_cycle.htm","Copying a Funding Cycle","﻿Copying a Funding Cycle To copy a funding cycle: 1. Click on the Copy button next to the desired Funding Cycle in the Funding Cycle Management se...",""],
["./administration_funding_cycle_managing_funding_cycles.htm","Managing Funding Cycles","﻿Adding a Funding Cycle To add a funding cycle: 1. Click on the Add button from the Funding Cycle Management section of Program Management page. T...",""],
["./administration_funding_cycle_managing_funding_cycles_default_grantee_reporting_schedule.htm","Default Grantee Reporting Schedule","﻿Setting Up the Default Grantee Reporting Schedule The Default Grantee Reports Parameters for Funding Cycle section allows the user to create a st...",""],
["./administration_funding_cycle_managing_funding_cycles_default_payment_schedule.htm","Default Payment Schedule","﻿Setting Up the Default Payment Schedule The Default Payment Parameters for Funding Cycle section allows the user to create a standard payment sch...",""],
["./administration_funding_cycle_managing_the_funding_cycle_workflow.htm","Adding and Managing the Funding Cycle Workflow","﻿Adding and Managing the Funding Cycle Workflow For each Funding Cycle, a specific workflow, or path for the grant lifecycle, can be created using...",""],
["./administration_funding_cycle_managing_the_funding_cycle_workflow_eligibility_workflow_builder.htm","Eligibility Workflow Builder","﻿Eligibility Workflow Builder The Eligibility Workflow Builder allows the user to select the eligibility task to be completed as part of the workf...",""],
["./administration_funding_opportunity.htm","Funding Opportunities","﻿Funding Opportunities All Funding Opportunities for a selected Program are listed in order of the Funding Opportunity ID in the Funding Opportuni...",""],
["./administration_funding_opportunity_managing_funding_opportunities.htm","Managing Funding Opportunities","﻿Managing Funding Opportunities To add a funding opportunity: 1. Click on the Add button from the Funding Opportunity Management section of the Pr...",""],
["./administration_funds.htm","Funds","﻿Funds The funds section allows the administrative user to designate the G/L accounts that will be used for grant payments. The total amount of th...",""],
["./administration_funds_managing_funds.htm","Managing Funds","﻿Managing Funds To add a fund: 1. Click on the Add button in the Grant Funds section of the Grant Funds page. The Grant Fund Editor page is displa...",""],
["./administration_imports.htm","Import","﻿Import The Import functionality allows users to import specific data in Excel format to certain sections of Easygrants system . The import proces...",""],
["./administration_imports_current_requests.htm","Current Import Requests","﻿Current Import Requests The Current Import Requests Listing page allows the user to view the request, remove the request from the import process,...",""],
["./administration_imports_historical_requests.htm","Historical Import Requests","﻿Historical Import Requests The Historical Import Requests Listing page allows the user to view previously imported requests. To view historical r...",""],
["./administration_imports_new_import.htm","New Import","﻿New Import To import the new file into Easygrants: 1. Click on the Import New File button in the New Import section of the Import Management page...",""],
["./administration_lookup_tables.htm","Lookup Tables","﻿Lookup Tables The Lookup Tables section allows the maintenance of the checklist or drop-down values used throughout Easygrants. For example, the ...",""],
["./administration_lookup_tables_adding_values.htm","Managing Lookup Table Values","﻿Managing Lookup Table Values To access the list of values for a particular lookup table, click on the Edit button next to the desired record in t...",""],
["./administration_maintenance_alerts.htm","Maintenance Alerts","﻿Maintenance Alerts The Maintenance Alerts functionality allows the administrative user to display messages to all Easygrants users on the Log In ...",""],
["./administration_maintenance_alerts_management.htm","Maintenance Alert Management","﻿Maintenance Alert Management To Manage the Maintenance Alert Messages: In the Maintenance Alerts Page: 1. Enter the desired plain text and HTML c...",""],
["./administration_programs.htm","System Management","﻿System Management Within the Configuration section of the Easygrants Manager, administrative users can set up new or modify existing Programs, Fu...",""],
["./administration_programs_adding_a_program.htm","Programs","﻿Programs All programs are listed in order of the Program ID in the Program Management section of the System Management page. Program setup and ma...",""],
["./administration_programs_managing_programs.htm","Managing Programs","﻿Managing Programs To add a program: 1. Click on the Add button from the Program Management section of the Program Management Page. The Program Ed...",""],
["./administration_reminders.htm","Reminders","﻿Reminders The reminders functionality allows staff and administrative users the ability to set up automatic correspondence to applicants and gran...",""],
["./administration_reminders_adding_a_reminder.htm","Managing Reminders","﻿Managing Reminders To add a reminder e-mail message: 1. Click on the Add button in the Reminders section of the Reminders page. The Reminder Edit...",""],
["./administration_system_settings.htm","System Settings","﻿System Settings The System Settings section allows the administrator to manage features that affect the system and are used throughout Easygrants...",""],
["./administration_system_settings_label_manager.htm","Label Manager","﻿Label Manager The Label Manager feature allows the administrator to enter a Preferred Label Name to display for a select number of fields through...",""],
["./administration_system_settings_label_manager_2.htm","Event Manager","﻿Event Manager The Event Manager feature allows the administrator to specify advanced data manipulation and updates (\"events\") that can be trigger...",""],
["./administration_system_settings_sharepoint_integration.htm","SharePoint Integration","﻿SharePoint Integration The SharePoint Integration feature allows the administrator to activate SharePoint Integration in Easygrants and enter tec...",""],
["./administration_tasks_deleting_a_task.htm","Grantee Reporting Workflow Builder","﻿Grantee Reporting Workflow Builder The Grantee Reporting Workflow Builder allows the user to select grantee report type tasks (e.g., Submit Progr...",""],
["./administration_tasks_deleting_a_task_2.htm","Grant Tasks Workflow Builder","﻿Grant Tasks Workflow Builder The Grant Tasks Workflow Builder allows the user to select grant amendment type tasks (e.g., Request No-cost Time Ex...",""],
["./administration_tasks_deleting_a_task_2_2.htm","Workflow Builder Validation","﻿Workflow Builder Validation The Workflow Builder Validation allows the user to specify the requirements for submission of each task in that was a...",""],
["./administration_tasks_editing_task_details.htm","Review Workflow Builder","﻿Review Workflow Builder The Review Workflow Builder allows the user to select review type tasks (e.g., Submit Conflicts and Preferences, Submit P...",""],
["./administration_tasks_viewing_task_outcomes.htm","Application Workflow Builder","﻿Application Workflow Builder The Application Workflow Builder allows the user to select application type tasks (e.g., Submit Letter of Intent, Su...",""],
["./administration_tasks_viewing_task_outcomes_2_2_2_2.htm","Creating the Eligibility Quiz","﻿Creating the Eligibility Quiz The next step is to associate the questions that are completed by the potential grantee to determine their eligibil...",""],
["./administration_tasks_viewing_task_outcomes_2_2_2_2_2.htm","Setting up the Eligibility Workflow","﻿Setting up the Eligibility Workflow Once the eligibility task and associated questions have been selected, the next steps and communication can b...",""],
["./administration_tasks_viewing_task_outcomes_2_2_2_2_2_2.htm","Setting up the Third Party Workflow","﻿Setting up the Related Third Party Workflow As part of the application phase, the related third party workflow must also be set up. Third party w...",""],
["./administration_tasks_viewing_task_outcomes_2_2_2_2_2_2_2.htm","Setting up the Third Party Workflow","﻿Setting up the Related Third Party Workflow As part of the grantee reporting phase, the related third party workflow must also be set up. Third p...",""],
["./administration_tasks_viewing_task_outcomes_2_2_2_2_3.htm","Setting up the Application Workflow","﻿Setting up the Application Workflow Once the tasks have been selected, the next steps and communication can be set up based on the results, or ou...",""],
["./administration_tasks_viewing_task_outcomes_2_2_2_2_3_2.htm","Setting up the Review Workflow","﻿Setting up the Review Workflow Once the tasks have been selected, the next steps and communication can be set up based on the results, or outcome...",""],
["./administration_tasks_viewing_task_outcomes_2_2_2_2_3_2_2.htm","Setting up the Grantee Report Workflow","﻿Setting up the Grantee Reporting Workflow Once the tasks have been selected, the next steps and communication can be set up based on the results,...",""],
["./administration_tasks_viewing_task_outcomes_2_2_2_2_3_2_2_2.htm","Entering the Submission Validation","﻿Entering the Submission Validation Each form for the tasks included in the workflow can have associated requirements for submission (validation)....",""],
["./administration_tasks_viewing_task_outcomes_2_2_2_2_3_2_2_3.htm","Setting up the Grant Tasks Workflow","﻿Setting up the Grant Tasks Workflow Once the tasks have been selected, the next steps and communication can be set up based on the results, or ou...",""],
["./administration_tasks_viewing_task_outcomes_2_2_2_2_3_2_2_4.htm","Setting up the Third Party Workflow","﻿Setting up the Related Third Party Workflow As part of the Grant Tasks phase, the related third party workflow can also be set up. Third party wo...",""],
["./administration_tasks_viewing_task_outcomes_2_2_2_2_4.htm","Selecting the Eligibility Task","﻿Selecting the Eligibility Task To select the task to be included in the eligibility workflow: 1. Click on the Add button in the Eligibility Task ...",""],
["./administration_tasks_viewing_task_outcomes_2_3.htm","Selecting the Application Tasks","﻿Selecting the Application Tasks To select the tasks to be included in the application workflow: 1. Click on the Add button in the Application Tas...",""],
["./administration_tasks_viewing_task_outcomes_2_3_2.htm","Selecting the Review Tasks","﻿Selecting the Review Tasks To select the tasks to be included in the review workflow: 1. Click on the Add button in the Review Task Information s...",""],
["./administration_tasks_viewing_task_outcomes_2_3_2_2.htm","Selecting the Grantee Report Tasks","﻿Selecting the Grantee Report Tasks To select the tasks to be included in the grantee reporting workflow: 1. Click on the Add button in the Grante...",""],
["./administration_tasks_viewing_task_outcomes_2_3_2_2_2.htm","Modifying Task Dates","﻿Modifying Task Dates To modify the dates associated with the workflow tasks: 1. Click on the Modify Dates button in the Tasks section of the Work...",""],
["./administration_tasks_viewing_task_outcomes_2_3_2_2_4.htm","Selecting the Grant Tasks","﻿Selecting the Grant Tasks To select the tasks to be available to the public and staff users from the Grant File: 1. Click on the Add button in th...",""],
["./administration_task_assignments.htm","Task Assignments","﻿Task Assignments The Task Assignments Management feature allows the user to search for all task assignments in a particular Funding Cycle and to ...",""],
["./administration_task_builder.htm","Task Builder","﻿Task Builder The Task Builder section of the Administration module allows the creation of tasks that will be completed by Easygrants users, inclu...",""],
["./administration_task_builder_creating_eligibility_tasks.htm","Creating Eligibility Tasks","﻿Creating Eligibility Tasks To add a new eligibility task: 1. Click on the Add button in the Task Builder (Eligibility) section of the Task Builde...",""],
["./administration_task_builder_creating_tasks.htm","Creating Tasks","﻿Creating Tasks The Task Builder section on the Task Builder page allows the creation of task types other than eligibility such as application, in...",""],
["./administration_upload_manager.htm","Upload Manager","﻿Upload Manager The Upload Manager feature allows you to manage the upload types and templates used in Easygrants tasks. If a task is using the Up...",""],
["./administration_upload_manager_managing_upload_templates.htm","Managing Upload Templates","﻿Managing Upload Templates Managing the upload templates available to associate with an upload type is done in the Uploads Templates section from ...",""],
["./administration_upload_manager_managing_upload_types.htm","Managing Upload Types","﻿Managing Upload Types Managing the upload types available for selection is done in the Uploads Manager section from the Uploads tab. To add a new...",""],
["./administration_upload_manager_relating_uploads_to_tasks.htm","Relating Uploads to Tasks","﻿Relating Uploads to Tasks Upload requirements can be associated with a particular task in a funding cycle workflow through the Upload Task page. ...",""],
["./administration_viewing_task_assignments.htm","Viewing Task Assignments","﻿Viewing Task Assignments To display task assignments for a specific Funding Cycle: 1. Select the Program. The page will refresh and display the r...",""],
["./administration_workgroups.htm","Workgroups","﻿Workgroups The Workgroups feature allows the administrative user to assign staff or administrative user types to a group that does common tasks w...",""],
["./administration_workgroups_managing_workgroups.htm","Managing Workgroups","﻿Managing Workgroups To add a workgroup: 1. Click on the Add button in the Workgroup Management section of the page. The Workgroups Editor page is...",""],
["./applications.htm","Applications","﻿Applications The Applications section of the Easygrants Manager allows you to search for and access application task-related information includin...",""],
["./applications_searching_for_application_tasks.htm","Searching for Application Tasks","﻿Searching for Application Tasks To search for application type tasks: 1. Enter or select one or more search criteria contained in the Easylist Se...",""],
["./chcf_administration_security_groups.htm","CHCF: Security Groups","﻿Security Groups The Security Groups section allows the administrator to manage features that affect the system and are used throughout Easygrants...",""],
["./chcf_administration_security_groups_grants_administration.htm","CHCF: Grants Administration","﻿SharePoint Integration The Grants Administration Security Group allows the administrator to enter add or remove staff members or administrators t...",""],
["./chcf_home_page_planned_projects_reassigning_planned_projects.htm","CHCF: Reassigning Planned Projects","﻿Reassigning Planned Projects To reassign (or move) a planned project to another staff or administrative user&#39;s home page: 1. Click on the Reassig...",""],
["./chcf_home_page_planned_projects_reassigning_planned_projects_2.htm","Reassigning Planned Projects","﻿Reassigning Planned Projects To reassign a planned project to another staff or administrative user: 1. Click on the Reassign link for the desired...",""],
["./chcf_introduction_terminology.htm","CHCF: Terminology","﻿Terminology The Easygrants Online Guide provide terminology for the baseline software. Where possible, specific California HealthCare Foundation ...",""],
["./chcf_projects_project_details.htm","CHCF: Project Details","﻿Project Details The Project Details tab in the project file allows users to manage the staff and grants associated with the project. The project ...",""],
["./contacts.htm","Contacts","﻿Reassigning Planned Projects To reassign a planned project to another staff or administrative user: 1. Click on the Reassign link for the desired...",""],
["./contacts_adding_organization_records.htm","Adding Organization Records","﻿Adding Organization Records To add an organization: 1. Select Organization from the Add Contact Record section on the Contact Easylist page. Clic...",""],
["./contacts_adding_organization_records_resolving_matching_organization_records.htm","Resolving Matching Organization Records","﻿Resolving Matching Organization Records Upon saving the organization information, Easygrants checks for existing contact records based on the fol...",""],
["./contacts_adding_person_records.htm","Adding Person Records","﻿Adding Person Records To add the person contact: 1. Click on the Add button in the Add Contact Record section on the Contact Easylist page. The A...",""],
["./contacts_adding_person_records_resolving_matching_person_records.htm","Resolving Matching Person Records","﻿Resolving Matching Person Records Upon saving the person information, Easygrants checks for existing contact records based on the following: • An...",""],
["./contacts_organizations.htm","Organizations","﻿Organizations The organization record provides the functionality to view information related to organization contacts in Easygrants including: • ...",""],
["./contacts_organizations_activity.htm","Organization Contact Activity","﻿Organization Contact Activity The Activity tab in the Organization record displays grant records that the organization is associated with either ...",""],
["./contacts_organizations_attachments_managing_attachments.htm","Managing Organization Attachments","﻿Managing Organization Attachments To add an organization attachment : 1. Click the Add button in the File/Documents section of the Attachments pa...",""],
["./contacts_organizations_details.htm","Organization Details","﻿Organization Details The Organization Details tab of the organization contact record provides key information including the ability to modify the...",""],
["./contacts_organizations_details_managing_address.htm","Managing Organization Address Info","﻿Managing Organization Address Info Address information can be tracked at the organization level. The organization address information can include...",""],
["./contacts_organizations_details_managing_affiliated_organizations.htm","Managing Affiliated Organizations","﻿Managing Affiliated Organizations Organization affiliations can be managed in the Affiliated Organizations section of the Organization Details pa...",""],
["./contacts_organizations_details_managing_organization_contacts.htm","Managing Organization Contacts","﻿Managing Organization Contacts Organization person affiliations can be managed in the Organization Contacts section of the Organization Details p...",""],
["./contacts_organizations_details_managing_organization_information.htm","Managing Organization Information (Summary)","﻿Managing Organization Information (Summary) The organization name and primary information can be managed from the Summary section on the Organiza...",""],
["./contacts_organizations_details_managing_telephone_fax.htm","Managing Organization Telephone/Fax Info","﻿Managing Organization Telephone/Fax Info Telephone and fax number information can be tracked at the organization level. The organization telephon...",""],
["./contacts_organizations_details_managing_web_address.htm","Managing Organization Web Address Info","﻿Managing Organization Web Address Info Web address information can be tracked at the organization level. There can only be one primary Web addres...",""],
["./contacts_organizations_notes.htm","Organization Notes","﻿Organization Notes Organization notes allows staff users to track additional information related to the organization such as phone conversation i...",""],
["./contacts_organizations_notes_managing_notes.htm","Managing Organization Notes","﻿Managing Organization Notes To add an organization note: 1. Click on the Add button in the Add or Edit Note section of the Notes page. The Notes ...",""],
["./contacts_organization_attachments.htm","Organization Attachments","﻿Organization Attachments Organization attachments allows staff users to track related organization attachments such as tax information, negotiate...",""],
["./contacts_persons.htm","Persons","﻿Persons The person record provides the functionality to view information related to person contacts in Easygrants including: • Person Contact Det...",""],
["./contacts_persons_activity.htm","Person Contact Activity","﻿Person Contact Activity The Activity tab in the person contact record displays related grant activity including grant records for which the perso...",""],
["./contacts_persons_activity_viewing_application_tasks.htm","Viewing Application Tasks","﻿Viewing Person Application Tasks The Application Tasks section of the Person Contact Activity displays all workflow task assignments with the typ...",""],
["./contacts_persons_activity_viewing_grantee_reporting_tasks.htm","Viewing Grantee Reporting Tasks","﻿Viewing Person Grantee Reporting Tasks The Grantee Reporting Tasks section of the Person Contact Activity displays all workflow task assignments ...",""],
["./contacts_persons_activity_viewing_grant_projects.htm","Viewing Grant Projects","﻿Viewing Person Related Grant Projects The Grant Projects section of the Person Contact Activity page displays all grants for which the person con...",""],
["./contacts_persons_activity_viewing_review_tasks.htm","Viewing Review Tasks","﻿Viewing Person Review Tasks The Review Tasks section of the Person Contact Activity displays all workflow task assignments with the type of revie...",""],
["./contacts_persons_administration.htm","Person Contact Administration","﻿Person Contact Administration The Contact Administration page allows the staff users to manage the login and password information for the Easygra...",""],
["./contacts_persons_details.htm","Person Details","﻿Person Details The Person Details tab of the person contact record provides key information including the ability to modify the person informatio...",""],
["./contacts_persons_details_managing_address_info.htm","Managing Person Address Info","﻿Managing Person Address Info Address information can be tracked at the person level. The address information can include the office address, home...",""],
["./contacts_persons_details_managing_affiliated_organizations.htm","Managing Affiliated Organizations","﻿Managing Affiliated Organizations Organization affiliations can be managed in the Affiliated Organizations section of the Person Contact Details ...",""],
["./contacts_persons_details_managing_category_affiliations.htm","Managing Person Category Affiliations","﻿Managing Person Category Affiliations Person contacts can be affiliated to categories. The categories allow staff users to group person contact r...",""],
["./contacts_persons_details_managing_e_mail_address.htm","Managing Person E-mail Address Info","﻿Managing Person E-mail Address Info Multiple e-mail addresses can be tracked at the person contact level. The e-mail address information can incl...",""],
["./contacts_persons_details_managing_person_information.htm","Managing Person Information (Summary)","﻿Managing Person Information (Summary) The person contact name, gender, and contact restrictions can be managed from the Summary section on the Pe...",""],
["./contacts_persons_details_managing_telephone_fax.htm","Managing Person Telephone/Fax Info","﻿Managing Person Telephone/Fax Info Multiple telephone and fax numbers can be tracked at the person contact level. The person telephone/fax number...",""],
["./contacts_persons_details_managing_web_address.htm","Managing Person Web Address Info","﻿Managing Person Web Address Info Web address information can be tracked at the person level. There can only be one primary Web address for a pers...",""],
["./contacts_person_attachments_managing_attachments.htm","Person Attachments","﻿Person Attachments Contact Attachments allows staff users to track related person attachments such as resumes, biography, photos, or publications...",""],
["./contacts_person_correspondence.htm","Person Correspondence","﻿Person Correspondence The Correspondence page displays all e-mail correspondence sent and logged from Easygrants related to the person contact re...",""],
["./contacts_person_notes.htm","Person Notes","﻿Person Notes Contact Notes allows staff users to track additional information related to the person such as phone conversation information, inter...",""],
["./contacts_person_notes_managing_notes.htm","Managing Person Notes","﻿Managing Person Notes To add a person note: 1. Click on the Add button in the Add or Edit Note section of the Notes page. The Notes Editor page i...",""],
["./contacts_person_reviewer_information.htm","Reviewer Information","﻿Reviewer Information The Reviewer Info tab in the person contact record allows staff users to mark person contacts as a reviewer and input key re...",""],
["./contacts_person_reviewer_information_managing_assigned_review_committees.htm","Managing Assigned Review Committees","﻿Managing Assigned Review Committees From the Reviewer Information page, the reviewer can be assigned to review committees. To add a new committee...",""],
["./contacts_person_reviewer_information_managing_reviewer_info.htm","Managing Reviewer Information","﻿Managing Reviewer Information Person contacts can be designated as a reviewer in Easygrants making them available for searching in the Reviewers ...",""],
["./contacts_person_reviewer_information_viewing_review_tasks.htm","Viewing Review Tasks","﻿Viewing Review Tasks The Review Tasks section of the Person Reviewer Info page displays all workflow task assignments with the type of review to ...",""],
["./contacts_person_view_correspondence.htm","Viewing Person Correspondence","﻿Viewing Person Correspondence To view the correspondence e-mail details: 1. Click on the View button next to the desired record in the Correspond...",""],
["./contacts_searching_for_a_contact_advanced_search.htm","Searching for a Contact (Advanced Search)","﻿Searching for a Contact (Advanced Search) To search for a grant using the advanced search: 1. Enter or select one or more search criteria contain...",""],
["./contacts_searching_for_a_contact_quick_search.htm","Searching for a Contact (Quick Search)","﻿Searching for a Contact (Quick Search) To search for a grant using the quick search: 1. Enter or select one or more search criteria contained in ...",""],
["./create_tasks.htm","Create Tasks","﻿Create Tasks The Grant Tasks section allows users to create new tasks from within the Grant File. To create a new task: 1. Select a task from the...",""],
["./faq.htm","FAQ","﻿FAQ The FAQ feature allows the all users view frequently asked questions regarding Easygrants. Users will see a subset of the FAQs entered depend...",""],
["./glossary_of_easygrants_terms.htm","Glossary of Easygrants Terms","﻿Glossary of Easygrants Terms A Action: List of features that can be used to interact with a particular individual or task. C Categories: Contact ...",""],
["./glossary_of_philanthropic_terms.htm","Glossary of Philanthropic Terms","﻿Glossary of Philanthropic Terms 360-Degree Evaluation: A form of employee evaluation in which supervisors, subordinates, and colleagues participa...",""],
["./grantee_reports.htm","Grantee Reports","﻿Grantee Reports The Grantee Reports section of the Easygrants Manager allows you to search for and access grantee report task-related information...",""],
["./grantee_reports_searching_for_grantee_report_tasks.htm","Searching for Grantee Report Tasks","﻿Searching for Grantee Report Tasks To search for grantee report type tasks: 1. Enter or select one or more search criteria contained in the Easyl...",""],
["./grants.htm","Grants","﻿Grants The grant record provides the functionality to view and manage related information in Easygrants including: • Grant Details • Activity • C...",""],
["./grants_adding_a_grant.htm","Adding a Grant","﻿Adding a Grant To add a new grant: 1. Click on the Add Grant button in the Add Grant Record section of the Grants Easylist page. The Add Grant pa...",""],
["./grants_grant_activity.htm","Grant Activity","﻿Grant Activity The Grant Activity tab allows users to view and manage related task assignments and the project timeline for the grant. The grant ...",""],
["./grants_grant_activity_managing_the_project_timeline.htm","Managing the Project Timeline","﻿Managing the Project Timeline The Project Timeline section displays the milestones/activities for the grant work that will be completed by the gr...",""],
["./grants_grant_activity_task_assignment_history.htm","Task Assignment History","﻿Task Assignment History The Task Assignment History section of the Grant Activity page displays all workflow task assignments associated with the...",""],
["./grants_grant_contacts.htm","Grant Contacts","﻿Grant Contacts The Grant Contacts tab allows users to manage and view person and organization contacts related to the grant project. The grant co...",""],
["./grants_grant_contacts_applicantgrantee_primary_contact_history.htm","Applicant/Grantee Primary Contact History","﻿Applicant/Grantee Primary Contact History The Applicant/Grantee Primary Contact History section displays modifications made to the primary contac...",""],
["./grants_grant_contacts_managing_applicantgrantee_contacts.htm","Managing Applicant/Grantee Contacts","﻿Managing Applicant/Grantee Contacts The Applicant/Grantee Contacts section of the Grant Contacts page lists all of the applicant/grantee contacts...",""],
["./grants_grant_contacts_managing_other_related_organization_contacts.htm","Managing Other Related Organization Contacts","﻿Managing Other Related Organization Contacts The Other Related Organization Contacts section of the Grant Contacts page allows staff to manage or...",""],
["./grants_grant_contacts_managing_other_related_person_contacts.htm","Managing Other Related Person Contacts","﻿Managing Other Related Person Contacts The Other Related Person Contacts section of the Grant Contacts page allows staff to manage person contact...",""],
["./grants_grant_contacts_viewing_the_primary_contact.htm","Viewing the Primary Contact","﻿Replacing the Primary Contact/PI The Applicant/Grantee Primary Contact section of the Grant Contacts page displays the current primary contact as...",""],
["./grants_grant_contacts_viewing_third_party_contacts.htm","Viewing Third Party Contacts","﻿Replacing the Primary Contact/PI The Third Party Contacts section of the Grant Contacts page lists all of the third party contacts that were asso...",""],
["./grants_grant_demographics.htm","Grant Demographics","﻿Grant Demographics The Grant Demographics tab allows staff to view and manage the project participant demographic information. The demographics c...",""],
["./grants_grant_details.htm","Grant Details","﻿Grant Details The Grant Details tab in the grant file allows users to manage the staff associated with the grant, key grant information, and gran...",""],
["./grants_grant_details_affiliated_staff_history.htm","Affiliated Staff History","﻿Affiliated Staff History The Affiliated Staff History section displays all staff that were associated with the grant record from the created date...",""],
["./grants_grant_details_grant_financial_summary.htm","Grant Financial Summary","﻿Grant Financial Summary The Grant Financial Summary section displays summary information for awarded and payment amounts. The following fields ar...",""],
["./grants_grant_details_grant_status_history.htm","Grant Status History","﻿Grant Status History The Grant Status History section tracks changes in the Status field on the Grant Information Editor page. When a grant is cr...",""],
["./grants_grant_details_managing_affiliated_staff.htm","Managing Grant Affiliated Staff","﻿Managing Grant Affiliated Staff Staff and administrative users can be affiliated with a particular grant record for tracking the management of th...",""],
["./grants_grant_details_managing_grant_assurances.htm","Managing Grant Assurances","﻿Managing Grant Assurances Details of the Grant Assurances are displayed in the Grant Assurances section, including the usage of the grants. To ed...",""],
["./grants_grant_details_managing_grant_award_and_amendments.htm","Managing Grant Award and Amendments","﻿Managing Grant Award and Amendments The Grant Award and Amendments section allows staff and administrative users to enter an initial award amount...",""],
["./grants_grant_details_managing_grant_information.htm","Managing Grant Information","﻿Managing Grant Information The Grant Information section of the Grant Details page displays the key information for the grant including the grant...",""],
["./grants_grant_documents.htm","Grant Documents","﻿Grant Documents The Grant Documents tab allows staff to view and manage all documents related to the grant including full task summary documents ...",""],
["./grants_grant_documents_managing_private_documents.htm","Managing Private Documents","﻿Managing Private Documents The Private Documents section of the Grant Documents page allows users to upload documents to be shared only with othe...",""],
["./grants_grant_documents_managing_publications.htm","Managing Publications","﻿Managing Publications The Publications section allows staff to view and manage publications related to the grant work that is being done. Publica...",""],
["./grants_grant_documents_managing_public_documents.htm","Managing Public Documents","﻿Managing Public Documents The Public Documents section of the Grant Documents page allows users to upload documents to be shared with the grantee...",""],
["./grants_grant_documents_viewing_submitted_documents.htm","Viewing Submitted Documents","﻿Viewing Submitted Documents The Submitted Documents section of the Grant Documents page displays all documents that were uploaded as part of a ta...",""],
["./grants_grant_documents_viewing_summary_documents.htm","Viewing Summary Documents","﻿Viewing Summary Documents The Summary Documents section of the Grant Documents page displays all full task related submissions in PDF. The full t...",""],
["./grants_grant_financials.htm","Grant Financials","﻿Grant Financials The Grant Financials tab allows users to view and manage the budgets related to the grant (e.g., application, awarded, expenditu...",""],
["./grants_grant_financials_fund_allocation_summary.htm","Fund Allocation Summary","﻿Fund Allocation Summary The Fund Allocation Summary section displays summary information for each type of fund allocated to the grant. ",""],
["./grants_grant_financials_grant_fund_allocations_history.htm","Grant Fund Allocations History","﻿The Grant Fund Allocations History section tracks changes to the allocated funds for the grant. The Grant Fund Allocations History section will r...",""],
["./grants_grant_financials_managing_budgets.htm","Managing Budgets","﻿Managing Budgets From the Budgets section of the Grant Financials page, staff can add or modify budgets associated with the grant either entered ...",""],
["./grants_grant_financials_managing_grant_fund_allocations.htm","Managing Grant Fund Allocations","﻿Managing Grant Fund Allocations From the Grant Fund Allocations section, staff can designate funding sources for the grant and set the amount of ...",""],
["./grants_grant_financials_managing_the_payment_schedule.htm","Managing the Payment Schedule","﻿Managing the Payment Schedule From the Payment Schedule section of the Grant Financials page, staff can add or modify the payment information for...",""],
["./grants_grant_financials_managing_the_reporting_schedule.htm","Managing the Reporting Schedule","﻿Managing the Reporting Schedule From the Reporting Schedule section of the Grant Financials page, staff can add or modify the required reporting ...",""],
["./grants_grant_financials_payment_and_reporting_audit_trail.htm","Payment and Reporting Audit Trail","﻿Payment and Reporting Audit Trail The Payment and Reporting Audit Trail displays modifications made to the Payment or Reporting schedules. The mo...",""],
["./grants_grant_notes.htm","Grant Notes","﻿Grant Notes The Grant Notes functionality in the grant file allows staff and administrative users to add related notes to a particular grant reco...",""],
["./grants_media.htm","Grants Media","﻿Grant Media The Grant Media tab allows staff to view and manage all media events related to the grant. Media events are manually entered by Staff...",""],
["./grants_media_managing_links.htm","Managing Links","﻿Managing Links The Managing Links section of the Grant Media page allows staff users to enter links (i.e. Internet Addresses) representative of m...",""],
["./grants_media_managing_media.htm","Managing Media","﻿Managing Media The Managing Media section of the Grant Media page allows staff users to upload files representative of media events related to th...",""],
["./grants_media_managing_trips.htm","Managing Trips","﻿Managing Trips The Managing Trips section of the Grant Media page allows staff users to add information on trips taken associated to the grant. T...",""],
["./grants_searching_for_a_grant_advanced_search.htm","Searching for a Grant (Advanced Search)","﻿Searching for a Grant (Advanced Search) To search for a grant using the advanced search: 1. Enter or select one or more search criteria contained...",""],
["./grants_searching_for_a_grant_quick_search.htm","Searching for a Grant (Quick Search)","﻿Searching for a Grant (Quick Search) To search for a grant using the quick search: 1. Enter or select one or more search criteria contained in th...",""],
["./group_query_results.htm","Group Query Results","﻿Group Query Results The Group Query Results section of the Query Editor page allows you to group your query results by a particular field. This s...",""],
["./home_page.htm","Home Page","﻿Home Page The Home page contains links to the most commonly used features in the Easygrants Manager, such as personal task items and task items f...",""],
["./home_page_options.htm","Staff Home Page Options","﻿Staff Home Page Options The Options section on the staff home page provides the Staff and Administrative users with the ability change their pass...",""],
["./home_page_options_changing_your_password.htm","Changing Your Password","﻿Changing Your Password To change your password: 1. Click on the Change My Password link in the Options section of the Home page. The Change Passw...",""],
["./home_page_options_viewing_your_grants_portfolio.htm","Viewing Your Grants Portfolio","﻿Viewing Your Grants Portfolio To view your grants portfolio: 1. Click on the Go to My Grants Portfolio link in the Options section of the Home pa...",""],
["./home_page_personal_tasks.htm","Personal Tasks","﻿Personal Tasks All tasks assigned to you are listed in the Personal Tasks section of the Home page. Personal Tasks are assigned to the primary st...",""],
["./home_page_personal_tasks_accessing_personal_tasks.htm","Accessing Personal Tasks","﻿Accessing Personal Tasks To access the assigned tasks: 1. Click on the Task name link in the Task column. 2. Once in the task, follow the instruc...",""],
["./home_page_personal_tasks_reassigning_personal_tasks.htm","Reassigning Personal Tasks","﻿Reassigning Personal Tasks To reassign a task to another staff or administrative user: 1. Click on the Reassign link for the desired task. The Re...",""],
["./home_page_personal_tasks_submitting_internal_review.htm","Submitting Internal Review","﻿Reassigning Personal Tasks To reassign a task to another staff or administrative user: 1. Click on the Reassign link for the desired task. The Re...",""],
["./home_page_personal_tasks_submitting_internal_review_2.htm","Submitting Internal Review","﻿Reassigning Personal Tasks To reassign a task to another staff or administrative user: 1. Click on the Reassign link for the desired task. The Re...",""],
["./home_page_workgroup_tasks.htm","Submitting Internal Review","﻿Submitting Internal Review The Internal Review process is typically completed by staff members to determine the outcome of a submission, e.g., Su...",""],
["./home_page_workgroup_tasks_accessing_workgroup_tasks.htm","Accessing Workgroup Tasks","﻿Accessing Workgroup Tasks To perform a particular action on a workgroup task: 1. Select the desired activity in the Action drop-down list to the ...",""],
["./internal_review_resubmission.htm","Internal Review Resubmission","﻿Internal Review Resubmission The Resubmission process is typically initiated by staff members to request that the Applicant/Grantee resubmit some...",""],
["./introduction.htm","Introduction","﻿Introduction The Easygrants Manager provides access to all levels of grants management system administration and process management through one e...",""],
["./log_in_page.htm","Log In Page","﻿Log In The Log In page is the entry page for the Easygrants system. Easygrants uses pop-ups and cookies. Your Web browser and computer will need ...",""],
["./log_in_page_forgot_password.htm","Forgot Password","﻿Forgot Password If you have forgotten your login information: 1. Click on the Forgot your password? link. The Log In information retrieval page i...",""],
["./log_in_page_logging_in.htm","Logging In","﻿Logging In To log in to the Easygrants Manager: 1. Open the Internet Explorer Web browser (Internet Explorer 6.0 or higher is required for the Ea...",""],
["./mssc_contacts_persons_details_managing_affiliated_persons.htm","MSSC: Managing Affiliated Persons","﻿Managing Affiliated Persons Person contacts can be affiliated to other Persons. The affiliated persons allow staff users to affiliate person cont...",""],
["./mssc_contacts_persons_details_managing_person_information.htm","MSSC: Managing Person Information (Summary)","﻿Managing Person Information (Summary) The person contact name, gender, and contact restrictions can be managed from the Summary section on the Pe...",""],
["./navigation.htm","Navigation","﻿Navigating the Easygrants Manager Within the Easygrants Manager, staff and administrative users have access to tools that allow you to manage app...",""],
["./reports.htm","Reports","﻿Reports The Reports functionality provides the staff and administrative users access to: • Create and run basic queries using data collected in E...",""],
["./reports_advanced_queries.htm","Advanced Queries","﻿Running Advanced Queries The Advanced Queries section of the Reports module has not yet been implemented. ",""],
["./reports_basic_queries.htm","Basic Queries","﻿Running Basic Queries The Basic Query section of the Reports module allows users to find and run saved queries and create new queries based on Ea...",""],
["./reports_creating_a_new_query.htm","Creating a New Query","﻿Creating a New Query The Create New Query section of the Query/Report List page allows the user to create new dynamic reports for the data collec...",""],
["./reports_creating_a_new_query_filters.htm","Narrowing Query Results with Filters","﻿Narrowing Query Results with Filters The Filters section of the Query Tool Editor page allows you to narrow the report results set by creating co...",""],
["./reports_creating_a_new_query_query_results.htm","Finishing the Query","﻿Finishing the Query The Finish: Query Results section of the Query Editor page allows the user to view the query results and to save the query to...",""],
["./reports_creating_a_new_query_select_fields.htm","Seletcting Query Fields","﻿Selecting Query Fields The Select Fields section of the Query Editor page allows the selection of the fields or columns that need to be displayed...",""],
["./reports_creating_a_new_query_sort_fields.htm","Sorting Query Results","﻿Sorting Query Results The Sort Query Results section of the Query Tool Editor page allows you to display the report by the selected column name a...",""],
["./reports_custom_reports.htm","Custom Reports","﻿Custom Reports The Custom section of the Reports module will display any custom formatted reports created specific to a particular implementation. ",""],
["./reports_standard_reports.htm","Standard Reports","﻿Standard Reports The Standard section of the Reports module has not been implemented yet. ",""],
["./reports_word_merge.htm","Word Merge","﻿Word Merge The Word Merge section of the Reports module allows the user to upload templates to be used when selecting \"Word Merge\" from the Query...",""],
["./reviews.htm","Reviews","﻿Reviews The Reviews section of the Easygrants Manager allows you to manage the review cycles and stages and all aspects of review task items that...",""],
["./reviews_committees.htm","Committees","﻿Committees The Committees functionality allows the grouping of one or more reviewers with a designation of the committee role, e.g., Chair or Mem...",""],
["./reviews_committees_managing_committees.htm","Managing Committees","﻿Managing Committees To add a new committee: 1. Click on the Add button in the Committee Management section of the Committees page. The Committee ...",""],
["./reviews_committees_managing_committee_member_details.htm","Managing Committee Member Details","﻿Managing Committee Member Details From the Committee Members page you can view information on person contacts designated as committee members and...",""],
["./reviews_committees_notifying_a_committee.htm","Notifying a Committee","﻿Notifying a Committee An e-mail notification can be sent to all members of a committee. Most commonly, this function is used to notify committee ...",""],
["./reviews_review_processing.htm","Review Processing","﻿Review Processing The Review Processing section of the Easygrants Manager allows you to manage the committee (external) review. The external revi...",""],
["./reviews_review_processing_review_cycles.htm","Review Cycles","﻿Review Cycles Review Cycles are added in the Review Processing section of the Easygrants Manager. The review cycles features allows the user to: ...",""],
["./reviews_review_processing_review_cycles_adding_a_review_cycle.htm","Creating and Modifying Review Cycles","﻿Creating and Modifying Review Cycles To add a review cycle: 1. Click on the Add button in the Review Cycles section of the Review Cycles page. Th...",""],
["./reviews_review_processing_review_cycles_copying_a_review_cycle.htm","Copying a Review Cycle","﻿Copying a Review Cycle To copy of an existing review cycle: 1. Click on the Copy button next to the desired Review Cycle. 2. Click on the OK butt...",""],
["./reviews_review_processing_review_cycles_managing_a_review_cycle.htm","Managing a Review Cycle","﻿Managing a Review Cycle After a review cycle has been added, the next step is to configure the details of the review cycle, including identifying...",""],
["./reviews_review_processing_review_cycles_managing_a_review_cycle_selecting_review_cycle_part.htm","Selecting the Review Cycle Participants","﻿Selecting the Review Cycle Participants The first step in managing the review cycle is to select the review cycle participants. The participants ...",""],
["./reviews_review_processing_review_cycles_managing_a_review_cycle_selecting_review_cycle_part_sel_committee_incl.htm","Selecting the Committees to Include","﻿Selecting the Committees to Include To select the committees (reviewers) to include in the review cycle: 1. In the Committees to Include section,...",""],
["./reviews_review_processing_review_cycles_managing_a_review_cycle_selecting_review_cycle_part_sel_tsk_incl.htm","Selecting the Tasks to Include","﻿Selecting the Tasks to Include To select the participants (tasks) to include in the review cycle: 1. In the Tasks to Include section, select the ...",""],
["./reviews_review_processing_review_cycles_managing_a_review_cycle_set_rev_cycl_confl_pref.htm","Setting Review Cycle Conflicts and Preferences","﻿Setting Review Cycle Conflicts and Preferences The second step in managing the review cycle is to set the known review cycle conflicts and prefer...",""],
["./reviews_review_processing_review_cycles_managing_a_review_cycle_set_rev_cycl_confl_pref_man_c_p.htm","Manually Setting Conflicts and Preferences","﻿Manually Setting Conflicts and Preferences In addition to the bulk processing, conflicts and preferences for the review cycle can be viewed, set,...",""],
["./reviews_review_processing_review_cycles_managing_a_review_cycle_set_rev_cycl_confl_pref_man_c_p_man_c_p_com.htm","Managing Conflicts and Preferences by Committee","﻿Managing Conflicts and Preferences by Committee Conflicts and preferences can be viewed, set, and updated by committee within the View and Modify...",""],
["./reviews_review_processing_review_cycles_managing_a_review_cycle_set_rev_cycl_confl_pref_man_c_p_man_c_p_par.htm","Managing Conflicts and Preferences by Participant","﻿Managing Conflicts and Preferences by Participant Conflicts and preferences can be viewed, set, and updated by participant within the View and Mo...",""],
["./reviews_review_processing_review_cycles_managing_a_review_cycle_set_rev_cycl_confl_pref_man_c_p_man_c_p_rev.htm","Managing Conflicts and Preferences by Reviewer","﻿Managing Conflicts and Preferences by Reviewer Conflicts and preferences can be viewed, set, and updated by reviewer within the View or Modify Co...",""],
["./reviews_review_processing_review_cycles_managing_a_review_cycle_set_rev_cycl_confl_pref_sel_run_preproc.htm","Selecting and Running Preprocessing","﻿Selecting and Running Preprocessing Review Cycle conflicts and preferences can be assigned in bulk using the preprocessing options. To assign con...",""],
["./reviews_review_processing_review_cycles_managing_a_review_cycle_set_rev_cycl_confl_pref_viewing_conflicts_pref.htm","Viewing Conflicts and Preferences","﻿Viewing Conflicts and Preferences After conflicts and preferences are entered, the results are viewable in the View and Modify Conflicts and Pref...",""],
["./reviews_review_processing_review_stages.htm","Review Stages","﻿Review Stages Once the Review Cycle details have been completed, the review stages for that cycle are created. Each review stage corresponds to a...",""],
["./reviews_review_processing_review_stages_adding_a_review_stage.htm","Creating and Modifying Review Stages","﻿Creating and Modifying Review Stages To add a review stage for a review cycle: 1. Click on the Add button in the Review Stages section of the Rev...",""],
["./reviews_review_processing_review_stages_managing_a_review_stage.htm","Managing a Review Stage","﻿Managing a Review Stage After a review stage has been added, the next step is to configure the details of the review stage, including assigning p...",""],
["./reviews_review_processing_review_stages_managing_a_review_stage_assign_tasks_rev.htm","Assigning Tasks to Reviewers","﻿Assigning Tasks to Reviewers The first step in managing the review stage is to set the review assignments. Assigning reviews tasks to a reviewer ...",""],
["./reviews_review_processing_review_stages_managing_a_review_stage_assign_tasks_rev_select_run_bulk_assign.htm","Selecting and Running Bulk Assignments","﻿Selecting and Running Bulk Assignments Easygrants supports the creation of bulk (i.e., automatic) assignments of submissions to reviewers based o...",""],
["./reviews_review_processing_review_stages_managing_a_review_stage_assign_tasks_rev_view_man_set_assign.htm","Viewing and Manually Setting Assignments","﻿Viewing and Manually Setting Assignments Assigning the review tasks can be done in bulk (i.e., automatic) processing or manually assigned. The ma...",""],
["./reviews_review_processing_review_stages_managing_a_review_stage_assign_tasks_rev_view_man_set_assign_by_com.htm","Viewing Review Assignments by Committee","﻿Viewing Review Assignments by Committee To view review assignments by a committee: 1. Select the Committee name next to the View Assignments By C...",""],
["./reviews_review_processing_review_stages_managing_a_review_stage_assign_tasks_rev_view_man_set_assign_by_par.htm","Managing Review Assignments by Participant","﻿Managing Review Assignments by Participant Review assignments can be viewed, set, and updated by participant within the View and Modify Assignmen...",""],
["./reviews_review_processing_review_stages_managing_a_review_stage_assign_tasks_rev_view_man_set_assign_by_rev.htm","Managing Review Assignments by Reviewer","﻿Managing Review Assignments by Reviewer Review assignments can be viewed, set, and updated by reviewer within the View and Modify Assignments sec...",""],
["./reviews_review_processing_review_stages_managing_a_review_stage_calculating_average_scores_and_rankings.htm","Calculating Average Scores and Rankings","﻿Calculating Average Scores and Rankings The first step in determining final outcomes for a review stage is to calculate the average score and ran...",""],
["./reviews_review_processing_review_stages_managing_a_review_stage_managing_scores_and_comments.htm","Managing Scores and Comments","﻿Managing Scores and Comments The Review Stage Scores and Comments page allows the user to view, modify, and submit or unsubmit reviewer submissio...",""],
["./reviews_review_processing_review_stages_managing_a_review_stage_notifying_review_committee_members.htm","Notifying Review Committee Members","﻿Notifying Review Committee Members As the review stage opens, the review committee can be notified using the Review Notification page. To send th...",""],
["./reviews_review_processing_review_stages_managing_a_review_stage_setting_and_finalizing_outcomes.htm","Setting and Finalizing Outcomes for a Review Stage","﻿Setting and Finalizing Review Stage Outcomes The final step for a review stage is to set proposed and final stage or funding outcomes for the par...",""],
["./reviews_review_processing_review_stages_managing_scores_and_comments_managing_scores_and_comments_by_particip.htm","Managing Scores and Comments by Participant","﻿Managing Scores and Comments by Participant Review scores and comments can be viewed and updated by participant within the View and Modify Confli...",""],
["./reviews_review_processing_review_stages_managing_scores_and_comments_managing_scores_and_comments_by_reviewer.htm","Managing Scores and Comments by Reviewer","﻿Managing Scores and Comments by Reviewer Review scores and comments can be viewed and updated by reviewer within the View and Modify Conflicts/Pr...",""],
["./reviews_review_processing_review_stages_managing_scores_and_comments_viewing_the_variance_report.htm","Viewing the Variance Report","﻿Viewing the Variance Report From the Review Stage Scores and Comments page, the variance report can be generated and viewed. The variance report ...",""],
["./reviews_searching_for_a_reviewer.htm","Searching for a Reviewer","﻿Searching for a Reviewer The Reviewers Easylist page allows you to quickly search for and view information on person contacts designated as revie...",""],
["./reviews_searching_for_review_tasks.htm","Searching for Review Tasks","﻿Searching for Review Tasks The Reviews Easylist page allows you to quickly search for and view Review tasks that have been assigned to reviewers ...",""],
["./reviews_subcommittees.htm","Subcommittee","﻿Subcommittees The Subcommittees functionality supports the grouping of one or more reviewers from an existing committee allowing for a more detai...",""],
["./reviews_subcommittees_managing_subcommittees.htm","Managing Subcommittees","﻿Managing Subcommittees To add a new subcommittee: 1. Click on the Add button in the Subcommittee Management section of the Committees page. The S...",""],
["./reviews_subcommittees_managing_subcommittee_member_details.htm","Managing Subcommittee Member Detail","﻿Managing Subcommittee Member Details From the Subcommittee Members page you can view information on person contacts designated as subcommittee me...",""],
["./reviews_subcommittees_notifying_a_subcommittee.htm","Notifying a Subcommittee","﻿Notifying a Subcommittee An e-mail notification can be sent to all members of a sub committee. To notify members of a subcommittee: 1. Click on t...",""],
["./review_grantee_submission.htm","Review Grantee Submission","﻿Review Grantee Submission The Review Grantee Submission page allows the user to review a resubmission request before the request notice is sent t...",""]];
