set ANSI_NULLS OFF
set QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spGETID_RANGE_SEL]
(
	@table VARCHAR(255),
	@count INT = 1,
	@first_id INT = 0 OUTPUT,
	@last_id INT = 0 OUTPUT,
	@mode INT = NULL -- Select Only = 1; Return Only = 2
)
AS
SET NOCOUNT ON
DECLARE @FIRST_NEW_ID INT, @LAST_NEW_ID INT

BEGIN TRANSACTION NEWID
	SELECT @FIRST_NEW_ID = NEXT_ID FROM s_ID_GEN (ROWLOCK) WHERE TABLE_NAME = @table
	SET @LAST_NEW_ID = @FIRST_NEW_ID + @count
	UPDATE s_ID_GEN SET NEXT_ID = NEXT_ID + @count WHERE TABLE_NAME = @table
COMMIT TRANSACTION NEWID

IF @mode is NULL or @mode = 1
	SELECT @FIRST_NEW_ID AS FIRST_NEW_ID,
		@LAST_NEW_ID AS LAST_NEW_ID

SET @first_id = @FIRST_NEW_ID
SET @last_id = @LAST_NEW_ID

IF @mode is NULL or @mode = 2
	RETURN (@first_id)

SET NOCOUNT OFF



