USE [Easygrants]
GO
/****** Object:  Table [dbo].[LSC_c_REVIEW_AREA_OF_INQUIRY_SCORE]    Script Date: 02/25/2008 12:14:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LSC_c_REVIEW_AREA_OF_INQUIRY_SCORE](
[id] [int] NOT NULL,
[abbr] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[value] [decimal](18, 1) NULL,
[sort_order] [int] NULL,
[end_date] [datetime] NULL,
CONSTRAINT [PK_LSC_c_REVIEW_AREA_OF_INQUIRY_SCORE] PRIMARY KEY CLUSTERED
(
[id] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF