EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'AK-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NAK-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'AZ-2', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NAZ-5', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'CA-12', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'CA-14', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'CA-31', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'MCA', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'CT-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NCT-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'DE-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'MDE', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'GU-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'IA-3', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'MIA', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'ID-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'MID', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NID-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'KS-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'MKS', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'MA-10', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'MD-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'MMD', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'ME-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'MMX-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NME-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NMN-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'MP-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NMS-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'MNE', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NE-4', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NNE-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NH-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NJ-15', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'MNJ', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NJ-16', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NJ-18', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NJ-8', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NJ-12', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NJ-17', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NM-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NNM-2', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'MNM', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NNV-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NV-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'OH-17', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'OH-5', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'MOR', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NOR-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'OR-6', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'PA-25', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'PA-11', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'RI-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'MSC', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'MUT', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NUT-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'UT-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'VA-15', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'VA-16', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'VI-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'VT-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'MWA', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NWA-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'WA-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NWI-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'WI-2', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'MWV', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'NWY-1', @new_time_period_id = 17
EXEC spLSC_NEW_FUNDING_CYCLE @serv_area = 'WY-4', @new_time_period_id = 17
