rem set path=%path%;C:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\Binn;

set MSSQLSERVER_NAME=<<ENTER SERVER NAME HERE>>
set MSSQLSERVER_DBNAME=<<ENTER DATABASE NAME HERE>>

REM *****************************
REM EXECUTE	POST VERSION 5.3.1 UPGRADE SCRIPTS
REM *****************************

sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 01_Alter_GRANTEE_PROJECT_CONTACT_OTHER_PERSON.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 02_Alter_vEASYLIST_GRANTS.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 03_Alter_vEASYLIST_APPLICATIONS.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 04_Alter_vEASYLIST_CONTACTS_ORGANIZATION.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 05_Alter_vEASYLIST_CONTACTS_PERSON.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 06_Alter_vEASYLIST_GRANTEE_REPORTS.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 07_Update_a_CORRESPONDENCE_DEFINITION.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 08_ALTER_PROJECT_PAYMENT.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 09_Alter_vEASYLIST_GRANTEE_REPORTS.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 10_INSERT_a_WF_TASK_ROLE.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 11_ALTER_GRANTEE_PROJECT.sql