'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace Easygrants_Web.Modules.Staff.Controls.Page.Administration.TaskBuilder
    
    '''<summary>
    '''cTaskBuilderEditor class.
    '''</summary>
    '''<remarks>
    '''Auto-generated class.
    '''</remarks>
    Partial Public Class cTaskBuilderEditor
        
        '''<summary>
        '''spnTaskName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnTaskName As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spnNewTaskName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnNewTaskName As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spnDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnDescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spnCopy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnCopy As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnCancel As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spnConfigXML control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnConfigXML As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
