'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace Easygrants_Web.Modules.Staff.Controls.Page.Administration
    
    '''<summary>
    '''cPaymentImportViewHtml class.
    '''</summary>
    '''<remarks>
    '''Auto-generated class.
    '''</remarks>
    Partial Public Class cPaymentImportViewHtml
        
        '''<summary>
        '''Table1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table1 As Global.System.Web.UI.HtmlControls.HtmlTable
        
        '''<summary>
        '''spnFileName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnFileName As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spnSubmitDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnSubmitDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spnImportResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnImportResult As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spnDataList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnDataList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''tblCloseWindow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblCloseWindow As Global.System.Web.UI.HtmlControls.HtmlTable
        
        '''<summary>
        '''spnClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnClose As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spnCloseControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnCloseControl As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
