'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace Easygrants_Web.Modules.Staff.Controls.Page.Administration

	'''<summary>
	'''cpgImportViewHtml class.
	'''</summary>
	'''<remarks>
	'''Auto-generated class.
	'''</remarks>
	Partial Public Class cpgImportViewHtml

		'''<summary>
		'''Form1 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		'''<summary>
		'''spnPaymentImportViewHtml control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents spnPaymentImportViewHtml As Global.System.Web.UI.HtmlControls.HtmlGenericControl

		'''<summary>
		'''ctlPaymentImportViewHtml control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ctlPaymentImportViewHtml As Global.Easygrants_Web.Modules.Staff.Controls.Page.Administration.cPaymentImportViewHtml
	End Class
End Namespace
