rem set path=%path%;C:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\Binn;

set MSSQLSERVER_NAME=<<ENTER SERVER NAME HERE>>
set MSSQLSERVER_DBNAME=<<ENTER DATABASE NAME HERE>>

REM *****************************
REM EXECUTE	POST VERSION 5.3.4 UPGRADE SCRIPTS
REM *****************************

sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 01_Alter_spCREATE_DATABASE_LOG_TRIGGER.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 02_INSERT_a_EVENT_MANAGER_EVENT_TYPE.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 003_Update_s_SHAREPOINT_INTEGRATION.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 004_ALTER_spGENERATE_REVIEW_ASSIGNMENTS.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 005_ALTER_vEXTERNAL_REVIEW_APPLICATIONS_LIST.sql
sqlcmd -S %MSSQLSERVER_NAME% -d %MSSQLSERVER_DBNAME% -i 006_Alter_vWORK_GROUP_TO_DO_LIST.sql