--Reference Mantis 1835 and 2657

ALTER TABLE LSC_WF_TASK_ASSIGNMENT_AFFILIATIONS
	ADD organization_id INT NULL,
		time_period_id INT NULL
		
GO

ALTER TABLE LSC_WF_TASK_ASSIGNMENT_AFFILIATIONS
	ALTER COLUMN wf_task_assignment_id INT NULL