'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace Easygrants_Web.Modules.Staff.Controls.PageSection
    
    '''<summary>
    '''cHistoricalImportRequests class.
    '''</summary>
    '''<remarks>
    '''Auto-generated class.
    '''</remarks>
    Partial Public Class cHistoricalImportRequests
        
        '''<summary>
        '''ctlCrumbTrail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlCrumbTrail As Global.Core.Web.Navigation.CrumbTrail.cCrumbTrailDisplay
        
        '''<summary>
        '''Table1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table1 As Global.System.Web.UI.HtmlControls.HtmlTable
        
        '''<summary>
        '''spnDataList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnDataList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spnClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnClose As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
