GO
/****** Object:  Table [dbo].[ORGANIZATION_FISCAL_YEAR_AUDITED]    Script Date: 10/23/2008 09:41:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORGANIZATION_FISCAL_YEAR_AUDITED](
	[id] [int] NOT NULL,
	[organization_id] [int] NOT NULL,
	[organization_fiscal_year_id] [int] NULL,
 CONSTRAINT [PK_ORGANIZATION_FISCAL_YEAR_AUDITED] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]



INSERT INTO [s_ID_GEN]([table_name], [next_id], [is_code_table], [description]) 
	VALUES('ORGANIZATION_FISCAL_YEAR_AUDITED', 1, 0, NULL);