
ALTER TABLE REVIEW_COMMITTEE_MEMBER WITH NOCHECK ADD CONSTRAINT [Df_REVIEW_COMMITTEE_MEMBER_inactive] DEFAULT (0) FOR inactive
UPDATE REVIEW_COMMITTEE_MEMBER SET inactive=0 WHERE inactive is null
ALTER TABLE REVIEW_COMMITTEE_MEMBER ALTER COLUMN inactive bit  not null