ALTER VIEW [dbo].[vLSC_PAI_CASE_TOTAL]

AS

SELECT lsc_pai_case_id,
      ISNULL(Pro_Bono_CR, 0)
		  + ISNULL(Pro_Bono_CC, 0)
		  + ISNULL(Pro_Bono_AAR, 0)
		  + ISNULL(Pro_Bono_AAP, 0) pro_bono_total,
      ISNULL(Pro_Bono_S_CR, 0)
	      + ISNULL(Pro_Bono_S_CC, 0)
	      + ISNULL(Pro_Bono_S_AAR, 0)
	      + ISNULL(Pro_Bono_S_AAP, 0) pro_bono_s_total,
	  ISNULL(Judicare_CR, 0)
	      + ISNULL(Judicare_CC, 0)
	      + ISNULL(Judicare_AAR, 0)
		  + ISNULL(Judicare_AAP, 0) judicare_total,
	  ISNULL(Contr_Vol_CR, 0)
		  + ISNULL(Contr_Vol_CC, 0)
		  + ISNULL(Contr_Vol_AAR, 0)
		  + ISNULL(Contr_Vol_AAP, 0) contr_vol_total,
	  ISNULL(Contr_Indv_CR, 0)
		  + ISNULL(Contr_Indv_CC, 0)
		  + ISNULL(Contr_Indv_AAR, 0)
		  + ISNULL(Contr_Indv_AAP, 0) contr_indv_total,
	  ISNULL(Co_Council_CR, 0)
		  + ISNULL(Co_Council_CC, 0)
		  + ISNULL(Co_Council_AAR, 0)
		  + ISNULL(Co_Council_AAP, 0) co_counsel_total,
	  ISNULL(LRS_CR, 0)
		  + ISNULL(LRS_CC, 0)
		  + ISNULL(LRS_AAR, 0)
		  + ISNULL(LRS_AAP, 0) lrs_total,
	  ISNULL(Other_CR, 0)
		  + ISNULL(Other_CC, 0)
		  + ISNULL(Other_AAR, 0)
		  + ISNULL(Other_AAP, 0) other_total,
	  ISNULL(CoCounsel_PB_CR, 0)
		  + ISNULL(CoCounsel_PB_CC, 0)
		  + ISNULL(CoCounsel_PB_AAR, 0)
		  + ISNULL(CoCounsel_PB_AAP, 0) CoCounsel_PB_total,
	  ISNULL(CoCounsel_Comp_CR, 0)
		  + ISNULL(CoCounsel_Comp_CC, 0)
		  + ISNULL(CoCounsel_Comp_AAR, 0)
		  + ISNULL(CoCounsel_Comp_AAP, 0) CoCounsel_Comp_total,
	  ISNULL(Other_PB_CR, 0)
		  + ISNULL(Other_PB_CC, 0)
		  + ISNULL(Other_PB_AAR, 0)
		  + ISNULL(Other_PB_AAP, 0) Other_PB_total,
	  ISNULL(Other_Comp_CR, 0)
		  + ISNULL(Other_Comp_CC, 0)
		  + ISNULL(Other_Comp_AAR, 0)
		  + ISNULL(Other_Comp_AAP, 0) Other_Comp_total,
     ISNULL(Pro_Bono_CR, 0)
		  + ISNULL(Pro_Bono_S_CR, 0)
		  + ISNULL(Judicare_CR, 0)
		  + ISNULL(Contr_Vol_CR, 0)
		  + ISNULL(Contr_Indv_CR, 0)
		  + ISNULL(Co_Council_CR, 0)
		  + ISNULL(LRS_CR, 0)
		  + ISNULL(Other_CR, 0)
	  	  + ISNULL(CoCounsel_PB_CR, 0)
	  	  + ISNULL(CoCounsel_Comp_CR, 0)
	  	  + ISNULL(Other_PB_CR, 0)
	  	  + ISNULL(Other_Comp_CR, 0) cr_total,
	  ISNULL(Pro_Bono_CC, 0)
		  + ISNULL(Pro_Bono_S_CC, 0)
		  + ISNULL(Judicare_CC, 0)
		  + ISNULL(Contr_Vol_CC, 0)
		  + ISNULL(Contr_Indv_CC, 0)
		  + ISNULL(Co_Council_CC, 0)
		  + ISNULL(LRS_CC, 0)
		  + ISNULL(Other_CC, 0)
		  + ISNULL(CoCounsel_PB_CC, 0)
		  + ISNULL(CoCounsel_Comp_CC, 0)
		  + ISNULL(Other_PB_CC, 0)
		  + ISNULL(Other_Comp_CC, 0) cc_total,
	  ISNULL(Pro_Bono_AAR, 0)
		  + ISNULL(Pro_Bono_S_AAR, 0)
		  + ISNULL(Judicare_AAR, 0)
		  + ISNULL(Contr_Vol_AAR, 0)
		  + ISNULL(Contr_Indv_AAR, 0)
		  + ISNULL(Co_Council_AAR, 0)
		  + ISNULL(LRS_AAR, 0)
		  + ISNULL(Other_AAR, 0)
		  + ISNULL(CoCounsel_PB_AAR, 0)
		  + ISNULL(CoCounsel_Comp_AAR, 0)
		  + ISNULL(Other_PB_AAR, 0)
		  + ISNULL(Other_Comp_AAR, 0) aar_total,
	  ISNULL(Pro_Bono_AAP, 0)
		  + ISNULL(Pro_Bono_S_AAP, 0)
		  + ISNULL(Judicare_AAP, 0)
		  + ISNULL(Contr_Vol_AAP, 0)
		  + ISNULL(Contr_Indv_AAP, 0)
		  + ISNULL(Co_Council_AAP, 0)
		  + ISNULL(LRS_AAP, 0)
		  + ISNULL(Other_AAP, 0)
		  + ISNULL(CoCounsel_PB_AAP, 0) 
		  + ISNULL(CoCounsel_Comp_AAP, 0) 
		  + ISNULL(Other_PB_AAP, 0) 
		  + ISNULL(Other_Comp_AAP, 0)  aap_total,
      ISNULL(Pro_Bono_CR, 0)
      	  + ISNULL(Pro_Bono_S_CR, 0)
	  	  + ISNULL(CoCounsel_PB_CR, 0)
	  	  + ISNULL(Other_PB_CR, 0) all_pro_bono_cr,
	  ISNULL(Pro_Bono_CC, 0)
	      + ISNULL(Pro_Bono_S_CC, 0)
		  + ISNULL(CoCounsel_PB_CC, 0)
		  + ISNULL(Other_PB_CC, 0) all_pro_bono_cc,
	  ISNULL(Pro_Bono_AAR, 0)
	      + ISNULL(Pro_Bono_S_AAR, 0)
		  + ISNULL(CoCounsel_PB_AAR, 0)
		  + ISNULL(Other_PB_AAR, 0) all_pro_bono_aar,
	  ISNULL(Pro_Bono_AAP, 0) 
	      + ISNULL(Pro_Bono_S_AAP, 0) 
		  + ISNULL(CoCounsel_PB_AAP, 0) 
		  + ISNULL(Other_PB_AAP, 0) all_pro_bono_aap,
      ISNULL(Pro_Bono_CR, 0)
		  + ISNULL(Pro_Bono_CC, 0)
		  + ISNULL(Pro_Bono_AAR, 0)
		  + ISNULL(Pro_Bono_AAP, 0) 
      	  + ISNULL(Pro_Bono_S_CR, 0)
	      + ISNULL(Pro_Bono_S_CC, 0)
	      + ISNULL(Pro_Bono_S_AAR, 0)
	      + ISNULL(Pro_Bono_S_AAP, 0) 
	  	  + ISNULL(CoCounsel_PB_CR, 0)
		  + ISNULL(CoCounsel_PB_CC, 0)
		  + ISNULL(CoCounsel_PB_AAR, 0)
		  + ISNULL(CoCounsel_PB_AAP, 0) 
	  	  + ISNULL(Other_PB_CR, 0)
		  + ISNULL(Other_PB_CC, 0)
		  + ISNULL(Other_PB_AAR, 0)
		  + ISNULL(Other_PB_AAP, 0) all_pro_bono_total,
	  ISNULL(Judicare_CR, 0)
	  	  + ISNULL(Contr_Vol_CR, 0)
	  	  + ISNULL(Contr_Indv_CR, 0)
	  	  + ISNULL(CoCounsel_Comp_CR, 0)
	  	  + ISNULL(Other_Comp_CR, 0) compensated_cr,
	  ISNULL(Judicare_CC, 0)
		  + ISNULL(Contr_Vol_CC, 0)
		  + ISNULL(Contr_Indv_CC, 0)
		  + ISNULL(CoCounsel_Comp_CC, 0)
		  + ISNULL(Other_Comp_CC, 0) compensated_cc,
	  ISNULL(Judicare_AAR, 0)
		  + ISNULL(Contr_Vol_AAR, 0)
		  + ISNULL(Contr_Indv_AAR, 0)
		  + ISNULL(CoCounsel_Comp_AAR, 0)
		  + ISNULL(Other_Comp_AAR, 0) compensated_aar,
	  ISNULL(Judicare_AAP, 0) 
		  + ISNULL(Contr_Vol_AAP, 0) 
		  + ISNULL(Contr_Indv_AAP, 0) 
		  + ISNULL(CoCounsel_Comp_AAP, 0) 
		  + ISNULL(Other_Comp_AAP, 0) compensated_aap,
	  ISNULL(Judicare_CR, 0)
	      + ISNULL(Judicare_CC, 0)
	      + ISNULL(Judicare_AAR, 0)
		  + ISNULL(Judicare_AAP, 0) 
	  	  + ISNULL(Contr_Vol_CR, 0)
		  + ISNULL(Contr_Vol_CC, 0)
		  + ISNULL(Contr_Vol_AAR, 0)
		  + ISNULL(Contr_Vol_AAP, 0) 
	  	  + ISNULL(Contr_Indv_CR, 0)
		  + ISNULL(Contr_Indv_CC, 0)
		  + ISNULL(Contr_Indv_AAR, 0)
		  + ISNULL(Contr_Indv_AAP, 0) 
	  	  + ISNULL(CoCounsel_Comp_CR, 0)
		  + ISNULL(CoCounsel_Comp_CC, 0)
		  + ISNULL(CoCounsel_Comp_AAR, 0)
		  + ISNULL(CoCounsel_Comp_AAP, 0) 
	  	  + ISNULL(Other_Comp_CR, 0)
		  + ISNULL(Other_Comp_CC, 0)
		  + ISNULL(Other_Comp_AAR, 0)
		  + ISNULL(Other_Comp_AAP, 0) compensated_total,
     ISNULL(Pro_Bono_CR, 0)
		  + ISNULL(Pro_Bono_S_CR, 0)
		  + ISNULL(Judicare_CR, 0)
		  + ISNULL(Contr_Vol_CR, 0)
		  + ISNULL(Contr_Indv_CR, 0)
		  + ISNULL(Co_Council_CR, 0)
		  + ISNULL(LRS_CR, 0)
		  + ISNULL(Other_CR, 0)
	  	  + ISNULL(CoCounsel_PB_CR, 0)
	  	  + ISNULL(CoCounsel_Comp_CR, 0)
	  	  + ISNULL(Other_PB_CR, 0)
	  	  + ISNULL(Other_Comp_CR, 0)
		  + ISNULL(Pro_Bono_CC, 0)
		  + ISNULL(Pro_Bono_S_CC, 0)
		  + ISNULL(Judicare_CC, 0)
		  + ISNULL(Contr_Vol_CC, 0)
		  + ISNULL(Contr_Indv_CC, 0)
		  + ISNULL(Co_Council_CC, 0)
		  + ISNULL(LRS_CC, 0)
		  + ISNULL(Other_CC, 0)
		  + ISNULL(CoCounsel_PB_CC, 0)
		  + ISNULL(CoCounsel_Comp_CC, 0)
		  + ISNULL(Other_PB_CC, 0)
		  + ISNULL(Other_Comp_CC, 0)
		  + ISNULL(Pro_Bono_AAR, 0)
		  + ISNULL(Pro_Bono_S_AAR, 0)
		  + ISNULL(Judicare_AAR, 0)
		  + ISNULL(Contr_Vol_AAR, 0)
		  + ISNULL(Contr_Indv_AAR, 0)
		  + ISNULL(Co_Council_AAR, 0)
		  + ISNULL(LRS_AAR, 0)
		  + ISNULL(Other_AAR, 0)
		  + ISNULL(CoCounsel_PB_AAR, 0)
		  + ISNULL(CoCounsel_Comp_AAR, 0)
		  + ISNULL(Other_PB_AAR, 0)
		  + ISNULL(Other_Comp_AAR, 0)
		  + ISNULL(Pro_Bono_AAP, 0)
		  + ISNULL(Pro_Bono_S_AAP, 0)
		  + ISNULL(Judicare_AAP, 0)
		  + ISNULL(Contr_Vol_AAP, 0)
		  + ISNULL(Contr_Indv_AAP, 0)
		  + ISNULL(Co_Council_AAP, 0)
		  + ISNULL(LRS_AAP, 0)
		  + ISNULL(Other_AAP, 0)
		  + ISNULL(CoCounsel_PB_AAP, 0) 
		  + ISNULL(CoCounsel_Comp_AAP, 0) 
		  + ISNULL(Other_PB_AAP, 0) 
		  + ISNULL(Other_PB_AAP, 0) total,
	ISNULL(Pro_Bono_LSAR, 0)
		+ ISNULL(Pro_Bono_S_LSAR, 0)
		+ ISNULL(CoCounsel_PB_LSAR, 0)
		+ ISNULL(Other_PB_LSAR, 0) all_pro_bono_lsar,
	ISNULL(Judicare_LSAR, 0)
		+ ISNULL(Contr_Vol_LSAR, 0)
		+ ISNULL(Contr_Indv_LSAR, 0)
		+ ISNULL(CoCounsel_Comp_LSAR, 0)
		+ ISNULL(Other_Comp_LSAR, 0) compensated_lsar,
	ISNULL(Pro_Bono_LSAR, 0)
		+ ISNULL(Pro_Bono_S_LSAR, 0)
		+ ISNULL(CoCounsel_PB_LSAR, 0)
		+ ISNULL(Other_PB_LSAR, 0)
		+ ISNULL(Judicare_LSAR, 0)
		+ ISNULL(Contr_Vol_LSAR, 0)
		+ ISNULL(Contr_Indv_LSAR, 0)
		+ ISNULL(CoCounsel_Comp_LSAR, 0)
		+ ISNULL(Other_Comp_LSAR, 0) lsar_total,
	ISNULL(Pro_Bono_LSAP, 0)
		+ ISNULL(Pro_Bono_S_LSAP, 0)
		+ ISNULL(CoCounsel_PB_LSAP, 0)
		+ ISNULL(Other_PB_LSAP, 0) all_pro_bono_lsap,
	ISNULL(Judicare_LSAP, 0)
		+ ISNULL(Contr_Vol_LSAP, 0)
		+ ISNULL(Contr_Indv_LSAP, 0)
		+ ISNULL(CoCounsel_Comp_LSAP, 0)
		+ ISNULL(Other_Comp_LSAP, 0) compensated_lsap,
	ISNULL(Pro_Bono_LSAP, 0)
		+ ISNULL(Pro_Bono_S_LSAP, 0)
		+ ISNULL(CoCounsel_PB_LSAP, 0)
		+ ISNULL(Other_PB_LSAP, 0)
		+ ISNULL(Judicare_LSAP, 0)
		+ ISNULL(Contr_Vol_LSAP, 0)
		+ ISNULL(Contr_Indv_LSAP, 0)
		+ ISNULL(CoCounsel_Comp_LSAP, 0)
		+ ISNULL(Other_Comp_LSAP, 0) lsap_total,
	ISNULL(Pro_Bono_PLAR, 0)
		+ ISNULL(Pro_Bono_S_PLAR, 0)
		+ ISNULL(CoCounsel_PB_PLAR, 0)
		+ ISNULL(Other_PB_PLAR, 0) all_pro_bono_plar,
	ISNULL(Judicare_PLAR, 0)
		+ ISNULL(Contr_Vol_PLAR, 0)
		+ ISNULL(Contr_Indv_PLAR, 0)
		+ ISNULL(CoCounsel_Comp_PLAR, 0)
		+ ISNULL(Other_Comp_PLAR, 0) compensated_plar,
	ISNULL(Pro_Bono_PLAR, 0)
		+ ISNULL(Pro_Bono_S_PLAR, 0)
		+ ISNULL(CoCounsel_PB_PLAR, 0)
		+ ISNULL(Other_PB_PLAR, 0)
		+ ISNULL(Judicare_PLAR, 0)
		+ ISNULL(Contr_Vol_PLAR, 0)
		+ ISNULL(Contr_Indv_PLAR, 0)
		+ ISNULL(CoCounsel_Comp_PLAR, 0)
		+ ISNULL(Other_Comp_PLAR, 0) plar_total,
	ISNULL(Pro_Bono_PLAP, 0)
		+ ISNULL(Pro_Bono_S_PLAP, 0)
		+ ISNULL(CoCounsel_PB_PLAP, 0)
		+ ISNULL(Other_PB_PLAP, 0) all_pro_bono_plap,
	ISNULL(Judicare_PLAP, 0)
		+ ISNULL(Contr_Vol_PLAP, 0)
		+ ISNULL(Contr_Indv_PLAP, 0)
		+ ISNULL(CoCounsel_Comp_PLAP, 0)
		+ ISNULL(Other_Comp_PLAP, 0) compensated_plap,
	ISNULL(Pro_Bono_PLAP, 0)
		+ ISNULL(Pro_Bono_S_PLAP, 0)
		+ ISNULL(CoCounsel_PB_PLAP, 0)
		+ ISNULL(Other_PB_PLAP, 0)
		+ ISNULL(Judicare_PLAP, 0)
		+ ISNULL(Contr_Vol_PLAP, 0)
		+ ISNULL(Contr_Indv_PLAP, 0)
		+ ISNULL(CoCounsel_Comp_PLAP, 0)
		+ ISNULL(Other_Comp_PLAP, 0) plap_total
  FROM LSC_PAI_CASE